defmodule DoubleEntryLedger.BatchProcessor do
  @moduledoc """
  Pure fold over a batch of `:create_transaction` command inputs.

  This module implements `simulate_batch/2` — the in-memory simulation
  that decides which commands in a batch will succeed, which will fail,
  and what the merged post-batch account state looks like. It performs
  **no** DB calls, no IO, no system-time reads — all dynamic inputs are
  passed in by the caller.

  See `docs/superpowers/plans/2026-05-06-multi-command-batching.md`
  Section 4 for the full design.

  ## Input shape

  The fold consumes pre-extracted command inputs (Option B per the plan).
  Extracting entries from a `Command` struct requires DB access (account
  address → id resolution via `AccountStore`), so that step lives in the
  orchestrator (future step 5). The fold itself stays pure.

  Each input is a map:

      %{
        command:        Command.t(),
        transaction_id: Ecto.UUID.t(),       # generated upfront
        status:         :posted | :pending,
        entries:        [
          %{account_id: Ecto.UUID.t(), type: :debit | :credit, value: Money.t()}
        ]
      }

  ## Output

  See `t:write_plan/0`. `successes` are returned in claim order;
  `failures` likewise. `merged_accounts` only contains accounts that
  changed during the batch (untouched accounts are omitted so the
  writer can skip the `UPDATE`).
  """

  require Logger

  import Ecto.Query, only: [from: 2]

  alias DoubleEntryLedger.{Account, Balance, Command, Repo, Transaction}
  alias DoubleEntryLedger.Stores.BatchTransactionStoreHelper
  alias DoubleEntryLedger.Workers.CommandWorker.TransactionCommandTransformer

  @schema_prefix DoubleEntryLedger.Config.schema_prefix()

  @typedoc """
  Pre-extracted command input. `transaction_id` is generated by the
  orchestrator upfront so we don't depend on DB-generated IDs.
  """
  @type command_input :: %{
          command: Command.t(),
          transaction_id: Ecto.UUID.t(),
          status: :posted | :pending,
          entries: [entry()]
        }

  @typedoc "Plain-map entry as produced by the transformer (Money value)."
  @type entry :: %{
          account_id: Ecto.UUID.t(),
          type: :debit | :credit,
          value: Money.t() | %{amount: integer(), currency: atom()}
        }

  @typedoc """
  An entry plus the post-this-entry account snapshot, used by callers
  to write balance_history_entries. `account_after` reflects the state
  immediately after **this** entry was applied — not the post-batch
  state. This is essential for BHE per-entry granularity.
  """
  @type entry_with_snapshot :: %{
          account_id: Ecto.UUID.t(),
          type: :debit | :credit,
          value: Money.t() | %{amount: integer(), currency: atom()},
          account_after: Account.t()
        }

  @type success_record :: %{
          command: Command.t(),
          transaction_id: Ecto.UUID.t(),
          status: :posted | :pending,
          entries: [entry_with_snapshot()]
        }

  @typedoc """
  Reason payload for a failed command. Field/message pairs preserve
  the surface from `Account.compute_balance_changes/3` and friends.
  """
  @type failure_reason ::
          {:unbalanced}
          | {:account_not_found, Ecto.UUID.t()}
          | {:balance_change_error, atom(), String.t()}

  @type failure_record :: %{command: Command.t(), reason: failure_reason()}

  @type merged_account_state :: %{
          posted: Balance.t(),
          pending: Balance.t(),
          available: integer(),
          old_lock_version: integer(),
          new_lock_version: integer()
        }

  @type write_plan :: %{
          successes: [success_record()],
          failures: [failure_record()],
          merged_accounts: %{Ecto.UUID.t() => merged_account_state()}
        }

  @doc """
  Simulates a batch of `:create_transaction` commands against an
  in-memory map of accounts.

  Iterates the inputs in order. Each command applies all its entries
  atomically: every entry must validate against the running account
  state for the command to succeed. If any entry fails, the command's
  partial changes are dropped and the next command sees the **un**advanced
  state — matching legacy serial semantics.

  ## Parameters

    * `command_inputs` — list of `t:command_input/0` in claim order
    * `initial_accounts` — `%{account_id => Account.t()}` covering every
      account referenced by any entry in any command. Caller is
      responsible for the preload SELECT.

  ## Returns

  A `t:write_plan/0`. `successes` and `failures` are in claim order;
  `merged_accounts` only contains accounts whose `lock_version`
  advanced (i.e. were touched by at least one successful entry).

  Pure: no DB, no IO, no system-time reads.
  """
  @spec simulate_batch([command_input()], %{Ecto.UUID.t() => Account.t()}) :: write_plan()
  def simulate_batch(command_inputs, initial_accounts) when is_list(command_inputs) do
    initial_lock_versions = Map.new(initial_accounts, fn {id, acc} -> {id, acc.lock_version} end)

    initial_state = %{
      accounts: initial_accounts,
      successes: [],
      failures: []
    }

    final_state = Enum.reduce(command_inputs, initial_state, &fold_one_command/2)

    %{
      successes: Enum.reverse(final_state.successes),
      failures: Enum.reverse(final_state.failures),
      merged_accounts: build_merged_accounts(final_state.accounts, initial_lock_versions)
    }
  end

  # ── internals ─────────────────────────────────────────────────────

  @spec fold_one_command(command_input(), map()) :: map()
  defp fold_one_command(input, state) do
    case try_apply_command(state.accounts, input) do
      {:ok, advanced_accounts, success_record} ->
        %{state | accounts: advanced_accounts, successes: [success_record | state.successes]}

      {:error, reason} ->
        failure = %{command: input.command, reason: reason}
        # accounts unchanged: failed commands do not advance running state
        %{state | failures: [failure | state.failures]}
    end
  end

  @spec try_apply_command(map(), command_input()) ::
          {:ok, map(), success_record()} | {:error, failure_reason()}
  defp try_apply_command(accounts, %{status: status, entries: entries} = input)
       when status in [:posted, :pending] do
    with :ok <- assert_balanced(entries),
         {:ok, advanced_accounts, snapshots} <- apply_entries(accounts, entries, status) do
      {:ok, advanced_accounts,
       %{
         command: input.command,
         transaction_id: input.transaction_id,
         status: status,
         entries: Enum.reverse(snapshots)
       }}
    end
  end

  @spec assert_balanced([entry()]) :: :ok | {:error, failure_reason()}
  defp assert_balanced(entries) do
    case Transaction.assert_balanced(entries) do
      :ok -> :ok
      {:error, :unbalanced} -> {:error, {:unbalanced}}
    end
  end

  @spec apply_entries(map(), [entry()], :posted | :pending) ::
          {:ok, map(), [entry_with_snapshot()]} | {:error, failure_reason()}
  defp apply_entries(accounts, entries, status) do
    # Reduce_while over entries. Each successful entry advances a *local*
    # accounts copy; if any entry fails, the entire command rolls back —
    # so we discard the local copy and return the original `accounts` to
    # the caller via the error branch (state unchanged for this command).
    Enum.reduce_while(entries, {:ok, accounts, []}, fn entry, {:ok, accs, snaps} ->
      case Map.fetch(accs, entry.account_id) do
        {:ok, account} ->
          case Account.compute_balance_changes(account, entry, status) do
            {:ok, change} ->
              next_account = Account.apply_balance_change(account, change)
              snapshot = Map.put(entry, :account_after, next_account)
              {:cont, {:ok, Map.put(accs, account.id, next_account), [snapshot | snaps]}}

            {:error, field, message} ->
              {:halt, {:error, {:balance_change_error, field, message}}}
          end

        :error ->
          {:halt, {:error, {:account_not_found, entry.account_id}}}
      end
    end)
  end

  @spec build_merged_accounts(map(), map()) :: %{Ecto.UUID.t() => merged_account_state()}
  defp build_merged_accounts(final_accounts, initial_lock_versions) do
    Enum.reduce(final_accounts, %{}, fn {id, final}, acc ->
      old = Map.fetch!(initial_lock_versions, id)

      if old == final.lock_version do
        acc
      else
        Map.put(acc, id, %{
          posted: final.posted,
          pending: final.pending,
          available: final.available,
          old_lock_version: old,
          new_lock_version: final.lock_version
        })
      end
    end)
  end

  # ────────────────────────────────────────────────────────────────────
  # ── run_batch/2: Step 5 orchestrator ────────────────────────────────
  # ────────────────────────────────────────────────────────────────────

  @typedoc "Per-command success record returned by `run_batch/2`."
  @type success_summary :: %{command_id: Ecto.UUID.t(), transaction_id: Ecto.UUID.t()}

  @typedoc "Per-command failure record returned by `run_batch/2`."
  @type failure_summary :: %{command_id: Ecto.UUID.t(), reason: term()}

  @typedoc "Public return shape of `run_batch/2`."
  @type run_batch_result :: %{
          successes: [success_summary()],
          failures: [failure_summary()]
        }

  @doc """
  Orchestrates a batch of `:create_transaction` commands end-to-end:
  filters/extracts entries, preloads accounts, simulates the fold,
  writes the success CTE + failure UPDATE inside one `Repo.transaction/1`,
  and retries-with-split on `Ecto.StaleEntryError`.

  See `docs/superpowers/plans/2026-05-06-multi-command-batching.md`
  Section 5/8 for the full design.

  ## Behaviour summary

    * Empty input → `{:ok, %{successes: [], failures: []}}` immediately,
      no DB activity.
    * Commands whose `command_map.action` is not `:create_transaction`
      become failures with reason `{:unsupported_action, action}`.
    * Commands whose entries can't be extracted via
      `TransactionCommandTransformer.transaction_data_to_transaction_map/2`
      become failures with reason `{:transformer_error, reason}`.
    * Successful subset is folded with `simulate_batch/2`, then both
      writers run inside `Repo.transaction/1`.
    * On `Ecto.StaleEntryError`: re-preloads accounts, re-runs fold,
      retries up to `:max_batch_retries` times (default 3, configurable
      via `:double_entry_ledger, :max_batch_retries`).
    * On retry exhaustion AND `length(commands) > 1`: splits the batch
      in half and recurses on each half. Combines results.
    * On retry exhaustion with `length(commands) <= 1`: propagates
      `{:error, %Ecto.StaleEntryError{}}`.
    * On any other DB error: propagates `{:error, reason}` — the caller
      decides whether to fall back to per-cmd processing.

  ## Return shape

      {:ok, %{
        successes: [%{command_id: uuid, transaction_id: uuid}, ...],
        failures:  [%{command_id: uuid, reason: term},          ...]
      }}

  Order is not guaranteed to match input claim order; callers can
  re-sort by `command_id` if they need deterministic ordering.
  """
  @spec run_batch([Command.t()], Ecto.Repo.t()) ::
          {:ok, run_batch_result()} | {:error, term()}
  def run_batch(commands, repo \\ Repo)

  def run_batch([], _repo), do: {:ok, %{successes: [], failures: []}}

  def run_batch(commands, repo) when is_list(commands) do
    # One `now` for all rows in this logical batch (retries reuse it;
    # split recursion calls generate their own).
    now = DateTime.utc_now()
    started = System.monotonic_time()

    {command_inputs, initial_failures} = extract_inputs(commands)

    case write_with_retry(command_inputs, initial_failures, commands, repo, now, 0) do
      {:ok, write_plan} ->
        emit_per_command_telemetry(write_plan, System.monotonic_time() - started)
        {:ok, summarize(write_plan)}

      {:error, %Ecto.StaleEntryError{} = stale} ->
        # Retries exhausted on this batch. If we can split, split.
        # Otherwise (length 1 or 0) propagate.
        handle_split_or_give_up(commands, stale, repo)

      {:error, reason} ->
        {:error, reason}
    end
  end

  # Emit one synthetic `[:double_entry_ledger, :command, :process, :stop]`
  # event per successful command with `duration = batch_native / cmd_count`.
  # This keeps the same telemetry surface that legacy
  # `Telemetry.command_process_span/2` produces, so downstream consumers
  # (load tests, dashboards) see consistent per-cmd latency under either
  # path.
  defp emit_per_command_telemetry(%{successes: []}, _batch_duration), do: :ok

  defp emit_per_command_telemetry(%{successes: successes}, batch_duration) do
    per_cmd_duration = div(batch_duration, length(successes))

    Enum.each(successes, fn success ->
      :telemetry.execute(
        [:double_entry_ledger, :command, :process, :stop],
        %{duration: per_cmd_duration},
        %{
          command_id: success.command.id,
          instance_id: success.command.instance_id,
          source: :batch
        }
      )
    end)
  end

  # ── extract: filter unsupported actions + run transformer ────────

  # Returns {command_inputs_for_fold, initial_failure_records}.
  # Accepts a list of `Command.t()` and produces fold-ready inputs.
  @spec extract_inputs([Command.t()]) :: {[command_input()], [failure_record()]}
  defp extract_inputs(commands) do
    {inputs_rev, failures_rev} =
      Enum.reduce(commands, {[], []}, fn cmd, {inputs, failures} ->
        case extract_one(cmd) do
          {:ok, input} -> {[input | inputs], failures}
          {:error, failure} -> {inputs, [failure | failures]}
        end
      end)

    {Enum.reverse(inputs_rev), Enum.reverse(failures_rev)}
  end

  @spec extract_one(Command.t()) :: {:ok, command_input()} | {:error, failure_record()}
  defp extract_one(%Command{command_map: %{action: :create_transaction, payload: payload}} = cmd) do
    case TransactionCommandTransformer.transaction_data_to_transaction_map(
           payload,
           cmd.instance_id
         ) do
      {:ok, %{entries: entries, status: status}} when is_list(entries) ->
        # Stamp entry ids and a journal_event_id upfront so the fold's
        # `entry_with_snapshot` records carry their final ids and the
        # writer's CTEs can reference them without RETURNING coordination.
        stamped_entries =
          Enum.map(entries, fn entry ->
            Map.put_new_lazy(entry, :id, &Ecto.UUID.generate/0)
          end)

        {:ok,
         %{
           command: cmd,
           transaction_id: Ecto.UUID.generate(),
           journal_event_id: Ecto.UUID.generate(),
           status: status,
           entries: stamped_entries
         }}

      {:ok, _no_entries} ->
        # The transformer accepts empty/nil entries — but a batched
        # create with no entries is nonsensical. Reject.
        {:error, %{command: cmd, reason: {:transformer_error, :no_entries_provided}}}

      {:error, reason} ->
        {:error, %{command: cmd, reason: {:transformer_error, reason}}}
    end
  end

  defp extract_one(%Command{command_map: %{action: action}} = cmd) do
    {:error, %{command: cmd, reason: {:unsupported_action, action}}}
  end

  # ── preload: one SELECT for every account referenced ─────────────

  @spec preload_accounts([command_input()], Ecto.Repo.t()) ::
          %{Ecto.UUID.t() => Account.t()}
  defp preload_accounts([], _repo), do: %{}

  defp preload_accounts(command_inputs, repo) do
    ids =
      command_inputs
      |> Enum.flat_map(fn %{entries: entries} -> Enum.map(entries, & &1.account_id) end)
      |> Enum.uniq()

    case ids do
      [] ->
        %{}

      _ ->
        repo.all(from(a in Account, prefix: ^@schema_prefix, where: a.id in ^ids))
        |> Map.new(&{&1.id, &1})
    end
  end

  # ── simulate + write with retry on stale ─────────────────────────

  # Returns `{:ok, write_plan}` on success (containing all successes
  # AND all failures, to be summarized by `run_batch/2`), or
  # `{:error, %Ecto.StaleEntryError{}}` on retry exhaustion, or
  # `{:error, reason}` on any other DB error.
  @spec write_with_retry(
          [command_input()],
          [failure_record()],
          [Command.t()],
          Ecto.Repo.t(),
          DateTime.t(),
          non_neg_integer()
        ) :: {:ok, write_plan()} | {:error, term()}
  defp write_with_retry(command_inputs, initial_failures, commands, repo, now, attempt) do
    accounts = preload_accounts(command_inputs, repo)
    fold_plan = simulate_batch(command_inputs, accounts)

    # The pure fold builds a fresh success_record and doesn't carry
    # `:journal_event_id` through (that field is the orchestrator's
    # concern, not the fold's). Re-stamp from the input list — there's
    # a 1:1 mapping by `command.id`.
    journal_ids_by_command =
      Map.new(command_inputs, fn input -> {input.command.id, input.journal_event_id} end)

    successes_with_journal_ids =
      Enum.map(fold_plan.successes, fn success ->
        Map.put(
          success,
          :journal_event_id,
          Map.fetch!(journal_ids_by_command, success.command.id)
        )
      end)

    write_plan = %{
      successes: successes_with_journal_ids,
      failures: fold_plan.failures ++ initial_failures,
      merged_accounts: fold_plan.merged_accounts
    }

    case do_write(write_plan, repo, now) do
      :ok ->
        emit_telemetry(commands, write_plan, attempt)
        {:ok, write_plan}

      {:error, %Ecto.StaleEntryError{} = stale} ->
        max_retries = Application.get_env(:double_entry_ledger, :max_batch_retries, 3)

        if attempt >= max_retries do
          {:error, stale}
        else
          # Re-preload accounts (state has changed under us) and
          # re-run the fold. `now` and initial_failures stay the same.
          write_with_retry(
            command_inputs,
            initial_failures,
            commands,
            repo,
            now,
            attempt + 1
          )
        end

      {:error, reason} ->
        {:error, reason}
    end
  end

  # Wrap the writers in a Repo.transaction. Rescue StaleEntryError
  # OUTSIDE the transaction so the rollback completes cleanly.
  @spec do_write(write_plan(), Ecto.Repo.t(), DateTime.t()) :: :ok | {:error, term()}
  defp do_write(write_plan, repo, now) do
    repo.transaction(fn ->
      BatchTransactionStoreHelper.write_successes(write_plan, repo, now)
      BatchTransactionStoreHelper.write_failures(write_plan.failures, repo, now)
      :ok
    end)
    |> case do
      {:ok, :ok} -> :ok
      {:error, reason} -> {:error, reason}
    end
  rescue
    e in Ecto.StaleEntryError -> {:error, e}
  end

  # ── split-on-exhaustion ──────────────────────────────────────────

  defp handle_split_or_give_up(commands, stale, _repo) when length(commands) <= 1 do
    {:error, stale}
  end

  defp handle_split_or_give_up(commands, _stale, repo) do
    {left, right} = Enum.split(commands, div(length(commands), 2))

    with {:ok, left_result} <- run_batch(left, repo),
         {:ok, right_result} <- run_batch(right, repo) do
      {:ok,
       %{
         successes: left_result.successes ++ right_result.successes,
         failures: left_result.failures ++ right_result.failures
       }}
    end
  end

  # ── summarize: write_plan → public {successes, failures} ─────────

  @spec summarize(write_plan()) :: run_batch_result()
  defp summarize(write_plan) do
    successes =
      Enum.map(write_plan.successes, fn s ->
        %{command_id: s.command.id, transaction_id: s.transaction_id}
      end)

    failures =
      Enum.map(write_plan.failures, fn f ->
        %{command_id: f.command.id, reason: f.reason}
      end)

    %{successes: successes, failures: failures}
  end

  # ── telemetry ────────────────────────────────────────────────────

  defp emit_telemetry(commands, write_plan, attempt) do
    measurements = %{
      batch_size: length(commands),
      success_count: length(write_plan.successes),
      failure_count: length(write_plan.failures),
      retry_count: attempt
    }

    :telemetry.execute([:double_entry_ledger, :batch, :processed], measurements, %{})
  end
end
