defmodule DoubleEntryLedger.BatchProcessor do
  @moduledoc """
  Pure fold + orchestrator for batched `:create_transaction` and
  `:update_transaction` commands.

  `simulate_batch/2` is the in-memory simulation that decides which
  commands in a batch will succeed, which will fail, and what the
  merged post-batch account state looks like — no DB calls, no IO,
  no system-time reads. The orchestrator `run_batch/2` wraps it with
  the extraction, batched lookups, enrichment, write, and retry
  logic.

  ## Input shape (`t:command_input/0`)

  Build via `extract_one/1` (private). Creates produce the full shape
  at extraction time; updates are built in two stages because they
  need data from the existing pending transaction:

  Stage 1 — `extract_one/1` for `:update_transaction` produces a
  PARTIAL input with `:action`, `:command`, `:status`, `:entries`
  (NEW values from the transformer; or `[]` when the schema layer
  stripped them for `:archived`).

  Stage 2 — `enrich_updates_with_existing/2` (inside the retry loop)
  fills in `:transaction_id` (existing tx's id), `:transition`,
  `:journal_event_id`, and per-entry `:id` + `:old_value`. The fold
  and writer only ever see Stage 2.

  Creates skip Stage 2 — their `:transaction_id` / `:journal_event_id`
  are generated upfront in `extract_one/1`, and the entries already
  carry `:account_id`/`:type`/`:value` from the transformer.

  ## Output

  See `t:write_plan/0`. `successes` are returned in claim order;
  `failures` likewise. `merged_accounts` only contains accounts that
  changed during the batch (untouched accounts are omitted so the
  writer can skip the `UPDATE`).

  Same-batch dependency detection (`same_batch_dependency/1`) runs
  before enrichment to catch create→update or update→update
  collisions on the same `(instance_id, source, source_idempk)`
  triple and divert them to failures with the appropriate reason.
  """

  require Logger

  import Ecto.Query, only: [from: 2, dynamic: 2]

  alias DoubleEntryLedger.{
    Account,
    Balance,
    Command,
    Entry,
    PendingTransactionLookup,
    Repo,
    Transaction
  }

  alias DoubleEntryLedger.Stores.BatchTransactionStoreHelper
  alias DoubleEntryLedger.Workers.CommandWorker.TransactionCommandTransformer

  @schema_prefix DoubleEntryLedger.Config.schema_prefix()

  @typedoc """
  Pre-extracted command input. `transaction_id` is generated by the
  orchestrator upfront so we don't depend on DB-generated IDs.

  For `:create_transaction`, all fields are populated by `extract_one/1`
  before the fold runs.

  For `:update_transaction`, the input is built in two stages:
    * Stage 1 — `extract_one/1` produces `:action`, `:command`, `:status`,
      `:entries` (NEW values from the transformer). No `:transaction_id`,
      `:transition`, or `:journal_event_id` yet.
    * Stage 2 — `enrich_updates_with_existing/2` (see B4) adds
      `:transaction_id` (existing tx), `:journal_event_id` (new),
      `:transition`, and per-entry `:id` + `:old_value`. The fold
      (`simulate_batch/2`) only ever sees Stage 2.
  """
  @type command_input :: %{
          required(:command) => Command.t(),
          required(:action) => :create_transaction | :update_transaction,
          required(:status) => :posted | :pending | :archived,
          required(:entries) => [entry()],
          optional(:transaction_id) => Ecto.UUID.t(),
          optional(:journal_event_id) => Ecto.UUID.t(),
          optional(:transition) => :pending_to_posted | :pending_to_pending | :pending_to_archived
        }

  @typedoc """
  Plain-map entry as produced by the transformer (Money value).

  For `:update_transaction` Stage 2, entries also carry `:id` (existing
  entry id, re-used) and `:old_value` (the original value being
  reversed). Both are filled in by `enrich_updates_with_existing/2`.
  """
  @type entry :: %{
          required(:account_id) => Ecto.UUID.t(),
          required(:type) => :debit | :credit,
          required(:value) => Money.t() | %{amount: integer(), currency: atom()},
          optional(:id) => Ecto.UUID.t(),
          optional(:old_value) => Money.t() | %{amount: integer(), currency: atom()}
        }

  @typedoc """
  An entry plus the post-this-entry account snapshot, used by callers
  to write balance_history_entries. `account_after` reflects the state
  immediately after **this** entry was applied — not the post-batch
  state. This is essential for BHE per-entry granularity.
  """
  @type entry_with_snapshot :: %{
          required(:account_id) => Ecto.UUID.t(),
          required(:type) => :debit | :credit,
          required(:value) => Money.t() | %{amount: integer(), currency: atom()},
          required(:account_after) => Account.t(),
          optional(:id) => Ecto.UUID.t(),
          optional(:old_value) => Money.t() | %{amount: integer(), currency: atom()}
        }

  @type success_record :: %{
          required(:command) => Command.t(),
          required(:action) => :create_transaction | :update_transaction,
          required(:transaction_id) => Ecto.UUID.t(),
          required(:status) => :posted | :pending | :archived,
          required(:entries) => [entry_with_snapshot()],
          optional(:transition) => :pending_to_posted | :pending_to_pending | :pending_to_archived
        }

  @typedoc """
  Reason payload for a failed command. Field/message pairs preserve
  the surface from `Account.compute_balance_changes/3` and friends.
  """
  @type failure_reason ::
          {:unbalanced}
          | {:account_not_found, Ecto.UUID.t()}
          | {:balance_change_error, atom(), String.t()}

  @type failure_record :: %{command: Command.t(), reason: failure_reason()}

  @type merged_account_state :: %{
          posted: Balance.t(),
          pending: Balance.t(),
          available: integer(),
          old_lock_version: integer(),
          new_lock_version: integer()
        }

  @type write_plan :: %{
          successes: [success_record()],
          failures: [failure_record()],
          merged_accounts: %{Ecto.UUID.t() => merged_account_state()}
        }

  @doc """
  Simulates a batch of `:create_transaction` commands against an
  in-memory map of accounts.

  Iterates the inputs in order. Each command applies all its entries
  atomically: every entry must validate against the running account
  state for the command to succeed. If any entry fails, the command's
  partial changes are dropped and the next command sees the **un**advanced
  state — matching legacy serial semantics.

  ## Parameters

    * `command_inputs` — list of `t:command_input/0` in claim order
    * `initial_accounts` — `%{account_id => Account.t()}` covering every
      account referenced by any entry in any command. Caller is
      responsible for the preload SELECT.

  ## Returns

  A `t:write_plan/0`. `successes` and `failures` are in claim order;
  `merged_accounts` only contains accounts whose `lock_version`
  advanced (i.e. were touched by at least one successful entry).

  Pure: no DB, no IO, no system-time reads.
  """
  @spec simulate_batch([command_input()], %{Ecto.UUID.t() => Account.t()}) :: write_plan()
  def simulate_batch(command_inputs, initial_accounts) when is_list(command_inputs) do
    initial_lock_versions = Map.new(initial_accounts, fn {id, acc} -> {id, acc.lock_version} end)

    initial_state = %{
      accounts: initial_accounts,
      successes: [],
      failures: []
    }

    final_state = Enum.reduce(command_inputs, initial_state, &fold_one_command/2)

    %{
      successes: Enum.reverse(final_state.successes),
      failures: Enum.reverse(final_state.failures),
      merged_accounts: build_merged_accounts(final_state.accounts, initial_lock_versions)
    }
  end

  # ── internals ─────────────────────────────────────────────────────

  @spec fold_one_command(command_input(), map()) :: map()
  defp fold_one_command(input, state) do
    case try_apply_command(state.accounts, input) do
      {:ok, advanced_accounts, success_record} ->
        %{state | accounts: advanced_accounts, successes: [success_record | state.successes]}

      {:error, reason} ->
        failure = %{command: input.command, reason: reason}
        # accounts unchanged: failed commands do not advance running state
        %{state | failures: [failure | state.failures]}
    end
  end

  @spec try_apply_command(map(), command_input()) ::
          {:ok, map(), success_record()} | {:error, failure_reason()}
  defp try_apply_command(
         accounts,
         %{action: :update_transaction, transition: transition, entries: entries} = input
       ) do
    with :ok <- assert_balanced(entries),
         {:ok, advanced_accounts, snapshots} <- apply_entries(accounts, entries, transition) do
      {:ok, advanced_accounts,
       %{
         command: input.command,
         action: :update_transaction,
         transaction_id: input.transaction_id,
         status: input.status,
         transition: transition,
         entries: Enum.reverse(snapshots)
       }}
    end
  end

  defp try_apply_command(accounts, %{status: status, entries: entries} = input)
       when status in [:posted, :pending] do
    with :ok <- assert_balanced(entries),
         {:ok, advanced_accounts, snapshots} <- apply_entries(accounts, entries, status) do
      {:ok, advanced_accounts,
       %{
         command: input.command,
         action: :create_transaction,
         transaction_id: input.transaction_id,
         status: status,
         entries: Enum.reverse(snapshots)
       }}
    end
  end

  @spec assert_balanced([entry()]) :: :ok | {:error, failure_reason()}
  defp assert_balanced(entries) do
    case Transaction.assert_balanced(entries) do
      :ok -> :ok
      {:error, :unbalanced} -> {:error, {:unbalanced}}
    end
  end

  @spec apply_entries(map(), [entry()], DoubleEntryLedger.Types.trx_types()) ::
          {:ok, map(), [entry_with_snapshot()]} | {:error, failure_reason()}
  defp apply_entries(accounts, entries, trx) do
    # Reduce_while over entries. Each successful entry advances a *local*
    # accounts copy; if any entry fails, the entire command rolls back —
    # so we discard the local copy and return the original `accounts` to
    # the caller via the error branch (state unchanged for this command).
    Enum.reduce_while(entries, {:ok, accounts, []}, fn entry, {:ok, accs, snaps} ->
      case Map.fetch(accs, entry.account_id) do
        {:ok, account} ->
          case Account.compute_balance_changes(account, entry, trx) do
            {:ok, change} ->
              next_account = Account.apply_balance_change(account, change)
              snapshot = Map.put(entry, :account_after, next_account)
              {:cont, {:ok, Map.put(accs, account.id, next_account), [snapshot | snaps]}}

            {:error, field, message} ->
              {:halt, {:error, {:balance_change_error, field, message}}}
          end

        :error ->
          {:halt, {:error, {:account_not_found, entry.account_id}}}
      end
    end)
  end

  @spec build_merged_accounts(map(), map()) :: %{Ecto.UUID.t() => merged_account_state()}
  defp build_merged_accounts(final_accounts, initial_lock_versions) do
    Enum.reduce(final_accounts, %{}, fn {id, final}, acc ->
      old = Map.fetch!(initial_lock_versions, id)

      if old == final.lock_version do
        acc
      else
        Map.put(acc, id, %{
          posted: final.posted,
          pending: final.pending,
          available: final.available,
          old_lock_version: old,
          new_lock_version: final.lock_version
        })
      end
    end)
  end

  # ────────────────────────────────────────────────────────────────────
  # ── run_batch/2: Step 5 orchestrator ────────────────────────────────
  # ────────────────────────────────────────────────────────────────────

  @typedoc "Per-command success record returned by `run_batch/2`."
  @type success_summary :: %{command_id: Ecto.UUID.t(), transaction_id: Ecto.UUID.t()}

  @typedoc "Per-command failure record returned by `run_batch/2`."
  @type failure_summary :: %{command_id: Ecto.UUID.t(), reason: term()}

  @typedoc "Public return shape of `run_batch/2`."
  @type run_batch_result :: %{
          successes: [success_summary()],
          failures: [failure_summary()]
        }

  @doc """
  Orchestrates a batch of `:create_transaction` and
  `:update_transaction` commands end-to-end: filters/extracts entries,
  runs same-batch dep detection, preloads accounts, enriches update
  inputs from the existing transactions, simulates the fold, writes
  the success CTE + failure UPDATE inside one `Repo.transaction/1`,
  and retries-with-split on `Ecto.StaleEntryError`.

  ## Behaviour summary

    * Empty input → `{:ok, %{successes: [], failures: []}}` immediately,
      no DB activity.
    * Commands whose `command_map.action` is neither `:create_transaction`
      nor `:update_transaction` become failures with reason
      `{:unsupported_action, action}`.
    * Commands whose entries can't be extracted via
      `TransactionCommandTransformer.transaction_data_to_transaction_map/2`
      become failures with reason `{:transformer_error, reason}`.
    * Successful subset is folded with `simulate_batch/2`, then both
      writers run inside `Repo.transaction/1`.
    * On `Ecto.StaleEntryError`: re-preloads accounts, re-runs fold,
      retries up to `:max_batch_retries` times (default 3, configurable
      via `:double_entry_ledger, :max_batch_retries`).
    * On retry exhaustion AND `length(commands) > 1`: splits the batch
      in half and recurses on each half. Combines results.
    * On retry exhaustion with `length(commands) <= 1`: propagates
      `{:error, %Ecto.StaleEntryError{}}`.
    * On any other DB error: propagates `{:error, reason}` — the caller
      decides whether to fall back to per-cmd processing.

  ## Return shape

      {:ok, %{
        successes: [%{command_id: uuid, transaction_id: uuid}, ...],
        failures:  [%{command_id: uuid, reason: term},          ...]
      }}

  Order is not guaranteed to match input claim order; callers can
  re-sort by `command_id` if they need deterministic ordering.
  """
  @spec run_batch([Command.t()], Ecto.Repo.t()) ::
          {:ok, run_batch_result()} | {:error, term()}
  def run_batch(commands, repo \\ Repo)

  def run_batch([], _repo), do: {:ok, %{successes: [], failures: []}}

  def run_batch(commands, repo) when is_list(commands) do
    # One `now` for all rows in this logical batch (retries reuse it;
    # split recursion calls generate their own).
    now = DateTime.utc_now()
    started = System.monotonic_time()

    {command_inputs, initial_failures} = extract_inputs(commands)

    case write_with_retry(command_inputs, initial_failures, commands, repo, now, 0) do
      {:ok, write_plan} ->
        emit_per_command_telemetry(write_plan, System.monotonic_time() - started)
        {:ok, summarize(write_plan)}

      {:error, %Ecto.StaleEntryError{} = stale} ->
        # Retries exhausted on this batch. If we can split, split.
        # Otherwise (length 1 or 0) propagate.
        handle_split_or_give_up(commands, stale, repo)

      {:error, reason} ->
        {:error, reason}
    end
  end

  # Emit one synthetic `[:double_entry_ledger, :command, :process, :stop]`
  # event per successful command with `duration = batch_native / cmd_count`.
  # This keeps the same telemetry surface that legacy
  # `Telemetry.command_process_span/2` produces, so downstream consumers
  # (load tests, dashboards) see consistent per-cmd latency under either
  # path.
  defp emit_per_command_telemetry(%{successes: []}, _batch_duration), do: :ok

  defp emit_per_command_telemetry(%{successes: successes}, batch_duration) do
    per_cmd_duration = div(batch_duration, length(successes))

    Enum.each(successes, fn success ->
      :telemetry.execute(
        [:double_entry_ledger, :command, :process, :stop],
        %{duration: per_cmd_duration},
        %{
          command_id: success.command.id,
          instance_id: success.command.instance_id,
          source: :batch
        }
      )
    end)
  end

  # ── extract: filter unsupported actions + run transformer ────────

  # Returns {command_inputs_for_fold, initial_failure_records}.
  # Accepts a list of `Command.t()` and produces fold-ready inputs.
  @spec extract_inputs([Command.t()]) :: {[command_input()], [failure_record()]}
  defp extract_inputs(commands) do
    {inputs_rev, failures_rev} =
      Enum.reduce(commands, {[], []}, fn cmd, {inputs, failures} ->
        case extract_one(cmd) do
          {:ok, input} -> {[input | inputs], failures}
          {:error, failure} -> {inputs, [failure | failures]}
        end
      end)

    {Enum.reverse(inputs_rev), Enum.reverse(failures_rev)}
  end

  @spec extract_one(Command.t()) :: {:ok, command_input()} | {:error, failure_record()}
  defp extract_one(%Command{command_map: %{action: :create_transaction, payload: payload}} = cmd) do
    case TransactionCommandTransformer.transaction_data_to_transaction_map(
           payload,
           cmd.instance_id
         ) do
      {:ok, %{entries: entries, status: status}} when is_list(entries) ->
        # Stamp entry ids and a journal_event_id upfront so the fold's
        # `entry_with_snapshot` records carry their final ids and the
        # writer's CTEs can reference them without RETURNING coordination.
        stamped_entries =
          Enum.map(entries, fn entry ->
            Map.put_new_lazy(entry, :id, &Ecto.UUID.generate/0)
          end)

        {:ok,
         %{
           command: cmd,
           action: :create_transaction,
           transaction_id: Ecto.UUID.generate(),
           journal_event_id: Ecto.UUID.generate(),
           status: status,
           entries: stamped_entries
         }}

      {:ok, _no_entries} ->
        # The transformer accepts empty/nil entries — but a batched
        # create with no entries is nonsensical. Reject.
        {:error, %{command: cmd, reason: {:transformer_error, :no_entries_provided}}}

      {:error, reason} ->
        {:error, %{command: cmd, reason: {:transformer_error, reason}}}
    end
  end

  defp extract_one(%Command{command_map: %{action: :update_transaction, payload: payload}} = cmd) do
    case TransactionCommandTransformer.transaction_data_to_transaction_map(
           payload,
           cmd.instance_id
         ) do
      {:ok, %{entries: entries, status: status}} when is_list(entries) ->
        # Stage 1 partial input. `enrich_updates_with_existing/2` (B4)
        # fills in `:transaction_id`, `:journal_event_id`, `:transition`,
        # and per-entry `:id` + `:old_value` before the fold sees this.
        {:ok,
         %{
           command: cmd,
           action: :update_transaction,
           status: status,
           entries: entries
         }}

      {:ok, %{status: status}} ->
        # No entries in the payload — valid for updates because
        # `TransactionData.update_command_changeset/2` strips entries
        # for `:archived` (and for `:posted` with no entries).
        # Enrichment will populate `:entries` from the existing
        # transaction.
        {:ok,
         %{
           command: cmd,
           action: :update_transaction,
           status: status,
           entries: []
         }}

      {:error, reason} ->
        {:error, %{command: cmd, reason: {:transformer_error, reason}}}
    end
  end

  defp extract_one(%Command{command_map: %{action: action}} = cmd) do
    {:error, %{command: cmd, reason: {:unsupported_action, action}}}
  end

  # ── preload: one SELECT for every account referenced ─────────────

  @spec preload_accounts([command_input()], Ecto.Repo.t()) ::
          %{Ecto.UUID.t() => Account.t()}
  defp preload_accounts([], _repo), do: %{}

  defp preload_accounts(command_inputs, repo) do
    ids =
      command_inputs
      |> Enum.flat_map(fn %{entries: entries} -> Enum.map(entries, & &1.account_id) end)
      |> Enum.uniq()

    case ids do
      [] ->
        %{}

      _ ->
        repo.all(from(a in Account, prefix: ^@schema_prefix, where: a.id in ^ids))
        |> Map.new(&{&1.id, &1})
    end
  end

  # ── simulate + write with retry on stale ─────────────────────────

  # Returns `{:ok, write_plan}` on success (containing all successes
  # AND all failures, to be summarized by `run_batch/2`), or
  # `{:error, %Ecto.StaleEntryError{}}` on retry exhaustion, or
  # `{:error, reason}` on any other DB error.
  @spec write_with_retry(
          [command_input()],
          [failure_record()],
          [Command.t()],
          Ecto.Repo.t(),
          DateTime.t(),
          non_neg_integer()
        ) :: {:ok, write_plan()} | {:error, term()}
  defp write_with_retry(command_inputs, initial_failures, commands, repo, now, attempt) do
    # B4 same-batch dep detection runs FIRST: same triple appearing on a
    # create+update (the update can't see the still-uncommitted create)
    # or on multiple updates (double-reversal) both produce diverted
    # failures with a more informative reason than the :create_command_*
    # check would yield. Idempotent across retries.
    {survivors, dep_failures} = same_batch_dependency(command_inputs)

    # B4 enrichment: load existing transactions for every surviving
    # :update_transaction input, run per-update validations, fill in
    # :transaction_id / :transition / :journal_event_id / per-entry
    # :id+:old_value. Updates that fail validation are diverted to
    # enrich_failures. Re-runs per retry attempt; results are NOT
    # carried across retries.
    {final_inputs, enrich_failures} = enrich_updates_with_existing(survivors, repo)

    # Preload accounts AFTER enrichment so that update inputs with
    # entries inferred from the existing transaction (e.g., :archived
    # whose payload entries were stripped by the schema layer) have
    # their account_ids populated and visible to preload_accounts/2.
    accounts = preload_accounts(final_inputs, repo)

    fold_plan = simulate_batch(final_inputs, accounts)

    # The pure fold builds a fresh success_record and doesn't carry
    # `:journal_event_id` through (that field is the orchestrator's
    # concern, not the fold's). Re-stamp from the (post-enrichment) input
    # list — there's a 1:1 mapping by `command.id`.
    journal_ids_by_command =
      Map.new(final_inputs, fn input -> {input.command.id, input.journal_event_id} end)

    successes_with_journal_ids =
      Enum.map(fold_plan.successes, fn success ->
        Map.put(
          success,
          :journal_event_id,
          Map.fetch!(journal_ids_by_command, success.command.id)
        )
      end)

    write_plan = %{
      successes: successes_with_journal_ids,
      failures: fold_plan.failures ++ dep_failures ++ enrich_failures ++ initial_failures,
      merged_accounts: fold_plan.merged_accounts
    }

    case do_write(write_plan, repo, now) do
      :ok ->
        emit_telemetry(commands, write_plan, attempt)
        {:ok, write_plan}

      {:error, %Ecto.StaleEntryError{} = stale} ->
        max_retries = Application.get_env(:double_entry_ledger, :max_batch_retries, 3)

        if attempt >= max_retries do
          {:error, stale}
        else
          # Re-preload accounts (state has changed under us) and
          # re-run the fold. `now` and initial_failures stay the same.
          write_with_retry(
            command_inputs,
            initial_failures,
            commands,
            repo,
            now,
            attempt + 1
          )
        end

      {:error, reason} ->
        {:error, reason}
    end
  end

  # Wrap the writers in a Repo.transaction. Rescue StaleEntryError
  # OUTSIDE the transaction so the rollback completes cleanly.
  @spec do_write(write_plan(), Ecto.Repo.t(), DateTime.t()) :: :ok | {:error, term()}
  defp do_write(write_plan, repo, now) do
    repo.transaction(fn ->
      BatchTransactionStoreHelper.write_successes(write_plan, repo, now)
      BatchTransactionStoreHelper.write_failures(write_plan.failures, repo, now)
      :ok
    end)
    |> case do
      {:ok, :ok} -> :ok
      {:error, reason} -> {:error, reason}
    end
  rescue
    e in Ecto.StaleEntryError -> {:error, e}
  end

  # ── split-on-exhaustion ──────────────────────────────────────────

  defp handle_split_or_give_up(commands, stale, _repo) when length(commands) <= 1 do
    {:error, stale}
  end

  defp handle_split_or_give_up(commands, _stale, repo) do
    {left, right} = Enum.split(commands, div(length(commands), 2))

    with {:ok, left_result} <- run_batch(left, repo),
         {:ok, right_result} <- run_batch(right, repo) do
      {:ok,
       %{
         successes: left_result.successes ++ right_result.successes,
         failures: left_result.failures ++ right_result.failures
       }}
    end
  end

  # ── summarize: write_plan → public {successes, failures} ─────────

  @spec summarize(write_plan()) :: run_batch_result()
  defp summarize(write_plan) do
    successes =
      Enum.map(write_plan.successes, fn s ->
        %{command_id: s.command.id, transaction_id: s.transaction_id}
      end)

    failures =
      Enum.map(write_plan.failures, fn f ->
        %{command_id: f.command.id, reason: f.reason}
      end)

    %{successes: successes, failures: failures}
  end

  # ── telemetry ────────────────────────────────────────────────────

  defp emit_telemetry(commands, write_plan, attempt) do
    measurements = %{
      batch_size: length(commands),
      success_count: length(write_plan.successes),
      failure_count: length(write_plan.failures),
      retry_count: attempt
    }

    :telemetry.execute([:double_entry_ledger, :batch, :processed], measurements, %{})
  end

  # ── B4: enrich Stage-1 update inputs with existing-transaction data ─

  # For every `:update_transaction` input, look up the existing pending
  # transaction (and its entries/accounts) via a single batched
  # `pending_transaction_lookup` SELECT, then enrich the input map with
  # `:transaction_id`, `:journal_event_id`, `:transition`, and per-entry
  # `:id` + `:old_value`. Inputs that fail a validation (`:create_command_*`,
  # `:transaction_not_pending`, `:entry_*`) are diverted to the failure
  # list; surviving update inputs are returned in their original position
  # relative to the create inputs (which pass through unchanged).
  #
  # Re-runs per retry attempt. Failures are recomputed from scratch each
  # attempt — a transaction may have flipped out of `:pending` between
  # attempts, demoting a candidate-success to `:transaction_not_pending`.
  @spec enrich_updates_with_existing([command_input()], Ecto.Repo.t()) ::
          {[command_input()], [failure_record()]}
  defp enrich_updates_with_existing(command_inputs, repo) do
    updates = Enum.filter(command_inputs, &(Map.get(&1, :action) == :update_transaction))

    case updates do
      [] ->
        {command_inputs, []}

      _ ->
        {enriched_by_cmd_id, failures} = build_enriched_map(updates, repo)
        {merge_enriched_into_inputs(command_inputs, enriched_by_cmd_id), failures}
    end
  end

  # Load every update target's lookup row in one SELECT, then reduce
  # over the updates to produce a `cmd.id => enriched_input` map plus a
  # list of per-update failures (lookup-not-found, validation errors).
  @spec build_enriched_map([command_input()], Ecto.Repo.t()) ::
          {%{Ecto.UUID.t() => command_input()}, [failure_record()]}
  defp build_enriched_map(updates, repo) do
    lookups_by_triple = load_lookups_batched(updates, repo)

    {enriched_map, fails_rev} =
      Enum.reduce(updates, {%{}, []}, fn input, acc ->
        enrich_one(input, lookups_by_triple, acc)
      end)

    {enriched_map, Enum.reverse(fails_rev)}
  end

  # Per-update step: look up the existing tx, pre-validate
  # (queue-item + tx state), pair entries to existing ones, and
  # assemble the Stage-2 input. `with` keeps the success path linear
  # and routes both lookup misses and validation errors to the
  # failure branch.
  defp enrich_one(input, lookups_by_triple, {enriched_map, fails}) do
    cmd = input.command

    with {:ok, lookup} <- Map.fetch(lookups_by_triple, triple_for(cmd)),
         {:ok, input} <- pre_validate(input, lookup),
         {:ok, enriched} <- pair_and_build(input, lookup) do
      {Map.put(enriched_map, cmd.id, enriched), fails}
    else
      :error -> {enriched_map, [failure(cmd, :create_command_not_found) | fails]}
      {:error, reason} -> {enriched_map, [failure(cmd, reason) | fails]}
    end
  end

  # Preserve claim order: keep creates pass-through, swap each update
  # for its enriched version in-place, drop updates that failed
  # enrichment (already recorded in failures). The fold and the BHE-CTE
  # both iterate this list in order, so claim order is what serializes
  # the per-entry `account_after` snapshots — matching legacy serial
  # semantics for mixed batches.
  @spec merge_enriched_into_inputs([command_input()], %{Ecto.UUID.t() => command_input()}) ::
          [command_input()]
  defp merge_enriched_into_inputs(command_inputs, enriched_map) do
    Enum.flat_map(command_inputs, fn input ->
      case Map.get(input, :action) do
        :update_transaction -> List.wrap(Map.get(enriched_map, input.command.id))
        _ -> [input]
      end
    end)
  end

  # Single batched SELECT loading every update target via the lookup
  # table. Each row carries the original create's command (with its
  # queue item) and the existing transaction (with its entries and
  # their accounts). Returned as a map indexed by
  # `{instance_id, source, source_idempk}` for O(1) lookup by the
  # per-update validator.
  @spec load_lookups_batched([command_input()], Ecto.Repo.t()) ::
          %{{Ecto.UUID.t(), String.t(), String.t()} => PendingTransactionLookup.t()}
  defp load_lookups_batched(updates, repo) do
    triples = Enum.map(updates, &triple_for(&1.command))

    where_clause =
      Enum.reduce(triples, false, fn {iid, src, sidempk}, acc ->
        dynamic(
          [ptl],
          (ptl.instance_id == ^iid and ptl.source == ^src and ptl.source_idempk == ^sidempk) or
            ^acc
        )
      end)

    repo.all(
      from(ptl in PendingTransactionLookup,
        prefix: ^@schema_prefix,
        where: ^where_clause,
        preload: [command: :command_queue_item, transaction: [entries: :account]]
      )
    )
    |> Map.new(fn lookup ->
      {{lookup.instance_id, lookup.source, lookup.source_idempk}, lookup}
    end)
  end

  # Validate the queue-item and target-transaction state, then
  # rehydrate the input's `:entries` from the existing transaction
  # when the transformer stripped them. Updates with status
  # `:archived` (or `:posted` with no payload entries) arrive with
  # `input.entries == []` because the schema layer strips entries in
  # those cases; `effective_entries/2` reconstructs them so the fold
  # can apply the transition (for `:archived` the new value defaults
  # to the existing one, which is what reverse_pending consumes).
  defp pre_validate(input, lookup) do
    cmd_status = lookup.command.command_queue_item.status
    tx = lookup.transaction

    cond do
      cmd_status == :dead_letter ->
        {:error, :create_command_in_dead_letter}

      cmd_status != :processed ->
        {:error, :create_command_not_processed}

      is_nil(tx) or tx.status != :pending ->
        {:error, :transaction_not_pending}

      true ->
        {:ok, %{input | entries: effective_entries(input.entries, tx.entries)}}
    end
  end

  # Match new entries to existing entries by account_id (per-pair
  # type-equality is enforced inside `pair_entries/2`) and assemble
  # the Stage-2 input on success.
  defp pair_and_build(input, lookup) do
    existing_entries = lookup.transaction.entries

    if length(input.entries) != length(existing_entries) do
      {:error, :entry_count_mismatch}
    else
      with {:ok, paired} <- pair_entries(input.entries, existing_entries) do
        {:ok, build_enriched_input(input, lookup, paired)}
      end
    end
  end

  defp effective_entries([], existing_entries) do
    Enum.map(existing_entries, fn e ->
      %{account_id: e.account_id, type: e.type, value: e.value}
    end)
  end

  defp effective_entries(payload_entries, _existing_entries), do: payload_entries

  # Pair each new-payload entry with exactly one existing entry by
  # `account_id`. Halts on the first mismatch (account or type).
  @spec pair_entries([entry()], [Entry.t() | map()]) ::
          {:ok, [{entry(), Entry.t() | map()}]}
          | {:error, :entry_account_mismatch | :entry_type_changed}
  defp pair_entries(new_entries, existing_entries) do
    existing_by_account_id = Map.new(existing_entries, &{&1.account_id, &1})

    result =
      Enum.reduce_while(new_entries, {:ok, []}, fn new_entry, {:ok, acc} ->
        case Map.fetch(existing_by_account_id, new_entry.account_id) do
          {:ok, existing} ->
            if new_entry.type == existing.type do
              {:cont, {:ok, [{new_entry, existing} | acc]}}
            else
              {:halt, {:error, :entry_type_changed}}
            end

          :error ->
            {:halt, {:error, :entry_account_mismatch}}
        end
      end)

    case result do
      {:ok, paired_rev} -> {:ok, Enum.reverse(paired_rev)}
      err -> err
    end
  end

  # All checks passed — produce the Stage-2 enriched command_input the
  # fold + writer expect.
  defp build_enriched_input(input, lookup, paired_entries) do
    transition =
      case input.status do
        :posted -> :pending_to_posted
        :pending -> :pending_to_pending
        :archived -> :pending_to_archived
      end

    enriched_entries =
      Enum.map(paired_entries, fn {new_entry, existing} ->
        new_entry
        |> Map.put(:id, existing.id)
        |> Map.put(:old_value, existing.value)
      end)

    Map.merge(input, %{
      transaction_id: lookup.transaction.id,
      journal_event_id: Ecto.UUID.generate(),
      transition: transition,
      entries: enriched_entries
    })
  end

  # ── B4: same-batch dependency detection ─────────────────────────────

  # Group enriched command_inputs by `(instance_id, source, source_idempk)`.
  # For each group:
  #   * single entry → pass through.
  #   * create + 1+ updates → keep the create(s), fail every update with
  #     `{:create_pending_in_batch, create_command_id}` (update can't see
  #     the still-uncommitted create's transaction yet).
  #   * 2+ updates, no create → keep the first update, fail the rest with
  #     `{:duplicate_update_in_batch, first_command_id}` (avoid
  #     double-reversal on the same target transaction).
  #   * 2+ creates, no update → pass through unchanged. The lookup table's
  #     unique constraint on `(instance_id, source, source_idempk)` is the
  #     pre-existing guard for this case.
  #
  # Idempotent across retries (operates only on static command_input
  # triples). Returns `{kept_inputs_in_original_order, failures}`.
  @spec same_batch_dependency([command_input()]) :: {[command_input()], [failure_record()]}
  defp same_batch_dependency(command_inputs) do
    by_triple =
      Enum.reduce(command_inputs, %{}, fn input, acc ->
        Map.update(acc, triple_for(input.command), [input], &[input | &1])
      end)

    {keep_ids, dep_failures} =
      Enum.reduce(by_triple, {MapSet.new(), []}, fn {_triple, group_rev}, acc ->
        group_rev
        |> Enum.reverse()
        |> classify_group()
        |> apply_group_classification(acc)
      end)

    kept = Enum.filter(command_inputs, &MapSet.member?(keep_ids, &1.command.id))
    {kept, Enum.reverse(dep_failures)}
  end

  # Tag a same-triple group by its shape. The handler clauses of
  # `apply_group_classification/2` decide what to keep and which
  # failures to record.
  @spec classify_group([command_input(), ...]) ::
          {:single, command_input()}
          | {:create_collision, [command_input(), ...], [command_input(), ...]}
          | {:duplicate_updates, [command_input(), ...]}
          | {:creates_only, [command_input(), ...]}
  defp classify_group([single]), do: {:single, single}

  defp classify_group(group) do
    {creates, updates} =
      Enum.split_with(group, &(Map.get(&1, :action) == :create_transaction))

    cond do
      creates != [] and updates != [] -> {:create_collision, creates, updates}
      length(updates) > 1 -> {:duplicate_updates, updates}
      true -> {:creates_only, creates}
    end
  end

  defp apply_group_classification({:single, input}, {keep_set, fails}) do
    {MapSet.put(keep_set, input.command.id), fails}
  end

  defp apply_group_classification({:create_collision, creates, updates}, {keep_set, fails}) do
    [first_create | _] = creates

    update_fails =
      Enum.map(updates, fn input ->
        failure(input.command, {:create_pending_in_batch, first_create.command.id})
      end)

    {add_all_to_keep(creates, keep_set), update_fails ++ fails}
  end

  defp apply_group_classification(
         {:duplicate_updates, [first_update | rest]},
         {keep_set, fails}
       ) do
    update_fails =
      Enum.map(rest, fn input ->
        failure(input.command, {:duplicate_update_in_batch, first_update.command.id})
      end)

    {MapSet.put(keep_set, first_update.command.id), update_fails ++ fails}
  end

  # All creates share the same triple, no updates. Pass through;
  # the lookup unique constraint catches it at write time.
  defp apply_group_classification({:creates_only, creates}, {keep_set, fails}) do
    {add_all_to_keep(creates, keep_set), fails}
  end

  defp add_all_to_keep(inputs, keep_set) do
    Enum.reduce(inputs, keep_set, fn input, ks -> MapSet.put(ks, input.command.id) end)
  end

  defp failure(%Command{} = cmd, reason), do: %{command: cmd, reason: reason}

  # The unique key the lookup table is indexed by — used wherever B4
  # groups, looks up, or compares commands by their idempotency identity.
  @spec triple_for(Command.t()) :: {Ecto.UUID.t(), String.t(), String.t()}
  defp triple_for(%Command{
         instance_id: iid,
         command_map: %{source: src, source_idempk: sidempk}
       }),
       do: {iid, src, sidempk}
end
