defmodule DoubleEntryLedger.BatchProcessor do
  @moduledoc """
  Pure fold over a batch of `:create_transaction` command inputs.

  This module implements `simulate_batch/2` — the in-memory simulation
  that decides which commands in a batch will succeed, which will fail,
  and what the merged post-batch account state looks like. It performs
  **no** DB calls, no IO, no system-time reads — all dynamic inputs are
  passed in by the caller.

  See `docs/superpowers/plans/2026-05-06-multi-command-batching.md`
  Section 4 for the full design.

  ## Input shape

  The fold consumes pre-extracted command inputs (Option B per the plan).
  Extracting entries from a `Command` struct requires DB access (account
  address → id resolution via `AccountStore`), so that step lives in the
  orchestrator (future step 5). The fold itself stays pure.

  Each input is a map:

      %{
        command:        Command.t(),
        transaction_id: Ecto.UUID.t(),       # generated upfront
        status:         :posted | :pending,
        entries:        [
          %{account_id: Ecto.UUID.t(), type: :debit | :credit, value: Money.t()}
        ]
      }

  ## Output

  See `t:write_plan/0`. `successes` are returned in claim order;
  `failures` likewise. `merged_accounts` only contains accounts that
  changed during the batch (untouched accounts are omitted so the
  writer can skip the `UPDATE`).
  """

  alias DoubleEntryLedger.{Account, Balance, Command, Transaction}

  @typedoc """
  Pre-extracted command input. `transaction_id` is generated by the
  orchestrator upfront so we don't depend on DB-generated IDs.
  """
  @type command_input :: %{
          command: Command.t(),
          transaction_id: Ecto.UUID.t(),
          status: :posted | :pending,
          entries: [entry()]
        }

  @typedoc "Plain-map entry as produced by the transformer (Money value)."
  @type entry :: %{
          account_id: Ecto.UUID.t(),
          type: :debit | :credit,
          value: Money.t() | %{amount: integer(), currency: atom()}
        }

  @typedoc """
  An entry plus the post-this-entry account snapshot, used by callers
  to write balance_history_entries. `account_after` reflects the state
  immediately after **this** entry was applied — not the post-batch
  state. This is essential for BHE per-entry granularity.
  """
  @type entry_with_snapshot :: %{
          account_id: Ecto.UUID.t(),
          type: :debit | :credit,
          value: Money.t() | %{amount: integer(), currency: atom()},
          account_after: Account.t()
        }

  @type success_record :: %{
          command: Command.t(),
          transaction_id: Ecto.UUID.t(),
          status: :posted | :pending,
          entries: [entry_with_snapshot()]
        }

  @typedoc """
  Reason payload for a failed command. Field/message pairs preserve
  the surface from `Account.compute_balance_changes/3` and friends.
  """
  @type failure_reason ::
          {:unbalanced}
          | {:account_not_found, Ecto.UUID.t()}
          | {:balance_change_error, atom(), String.t()}

  @type failure_record :: %{command: Command.t(), reason: failure_reason()}

  @type merged_account_state :: %{
          posted: Balance.t(),
          pending: Balance.t(),
          available: integer(),
          old_lock_version: integer(),
          new_lock_version: integer()
        }

  @type write_plan :: %{
          successes: [success_record()],
          failures: [failure_record()],
          merged_accounts: %{Ecto.UUID.t() => merged_account_state()}
        }

  @doc """
  Simulates a batch of `:create_transaction` commands against an
  in-memory map of accounts.

  Iterates the inputs in order. Each command applies all its entries
  atomically: every entry must validate against the running account
  state for the command to succeed. If any entry fails, the command's
  partial changes are dropped and the next command sees the **un**advanced
  state — matching legacy serial semantics.

  ## Parameters

    * `command_inputs` — list of `t:command_input/0` in claim order
    * `initial_accounts` — `%{account_id => Account.t()}` covering every
      account referenced by any entry in any command. Caller is
      responsible for the preload SELECT.

  ## Returns

  A `t:write_plan/0`. `successes` and `failures` are in claim order;
  `merged_accounts` only contains accounts whose `lock_version`
  advanced (i.e. were touched by at least one successful entry).

  Pure: no DB, no IO, no system-time reads.
  """
  @spec simulate_batch([command_input()], %{Ecto.UUID.t() => Account.t()}) :: write_plan()
  def simulate_batch(command_inputs, initial_accounts) when is_list(command_inputs) do
    initial_lock_versions = Map.new(initial_accounts, fn {id, acc} -> {id, acc.lock_version} end)

    initial_state = %{
      accounts: initial_accounts,
      successes: [],
      failures: []
    }

    final_state = Enum.reduce(command_inputs, initial_state, &fold_one_command/2)

    %{
      successes: Enum.reverse(final_state.successes),
      failures: Enum.reverse(final_state.failures),
      merged_accounts: build_merged_accounts(final_state.accounts, initial_lock_versions)
    }
  end

  # ── internals ─────────────────────────────────────────────────────

  @spec fold_one_command(command_input(), map()) :: map()
  defp fold_one_command(input, state) do
    case try_apply_command(state.accounts, input) do
      {:ok, advanced_accounts, success_record} ->
        %{state | accounts: advanced_accounts, successes: [success_record | state.successes]}

      {:error, reason} ->
        failure = %{command: input.command, reason: reason}
        # accounts unchanged: failed commands do not advance running state
        %{state | failures: [failure | state.failures]}
    end
  end

  @spec try_apply_command(map(), command_input()) ::
          {:ok, map(), success_record()} | {:error, failure_reason()}
  defp try_apply_command(accounts, %{status: status, entries: entries} = input)
       when status in [:posted, :pending] do
    with :ok <- assert_balanced(entries),
         {:ok, advanced_accounts, snapshots} <- apply_entries(accounts, entries, status) do
      {:ok, advanced_accounts,
       %{
         command: input.command,
         transaction_id: input.transaction_id,
         status: status,
         entries: Enum.reverse(snapshots)
       }}
    end
  end

  @spec assert_balanced([entry()]) :: :ok | {:error, failure_reason()}
  defp assert_balanced(entries) do
    case Transaction.assert_balanced(entries) do
      :ok -> :ok
      {:error, :unbalanced} -> {:error, {:unbalanced}}
    end
  end

  @spec apply_entries(map(), [entry()], :posted | :pending) ::
          {:ok, map(), [entry_with_snapshot()]} | {:error, failure_reason()}
  defp apply_entries(accounts, entries, status) do
    # Reduce_while over entries. Each successful entry advances a *local*
    # accounts copy; if any entry fails, the entire command rolls back —
    # so we discard the local copy and return the original `accounts` to
    # the caller via the error branch (state unchanged for this command).
    Enum.reduce_while(entries, {:ok, accounts, []}, fn entry, {:ok, accs, snaps} ->
      case Map.fetch(accs, entry.account_id) do
        {:ok, account} ->
          case Account.compute_balance_changes(account, entry, status) do
            {:ok, change} ->
              next_account = Account.apply_balance_change(account, change)
              snapshot = Map.put(entry, :account_after, next_account)
              {:cont, {:ok, Map.put(accs, account.id, next_account), [snapshot | snaps]}}

            {:error, field, message} ->
              {:halt, {:error, {:balance_change_error, field, message}}}
          end

        :error ->
          {:halt, {:error, {:account_not_found, entry.account_id}}}
      end
    end)
  end

  @spec build_merged_accounts(map(), map()) :: %{Ecto.UUID.t() => merged_account_state()}
  defp build_merged_accounts(final_accounts, initial_lock_versions) do
    Enum.reduce(final_accounts, %{}, fn {id, final}, acc ->
      old = Map.fetch!(initial_lock_versions, id)

      if old == final.lock_version do
        acc
      else
        Map.put(acc, id, %{
          posted: final.posted,
          pending: final.pending,
          available: final.available,
          old_lock_version: old,
          new_lock_version: final.lock_version
        })
      end
    end)
  end
end
