defmodule DoubleEntryLedger.Stores.BatchTransactionStoreHelper do
  @moduledoc """
  Executes the **success** half of a batched write — one CTE per
  Postgres round-trip — for a batch of `:create_transaction` commands.

  Consumes the output of `BatchProcessor.simulate_batch/2`. Failure
  handling lives in the sibling failure-UPDATE writer (Step 4).
  Wrapping in a `Repo.transaction/1` is the orchestrator's
  responsibility (Step 5).

  Behaviour-equivalent to the legacy `build_create/4` +
  `handle_build_transaction/3` path: same row shapes, same
  `pending_transaction_lookup` upsert behaviour, same
  optimistic-concurrency semantics on accounts.

  ## Strategy

  All UUIDs (transaction, entry, BHE, journal_event, lookup) are
  pre-generated by the fold so each CTE is independent — none
  references another CTE's `RETURNING`. The CTE bundle is just round-trip
  batching, not value chaining. This avoids tying CTE evaluation order
  to row order constraints.

  ## Stale lock_version detection

  `updated_accounts AS (UPDATE ... WHERE lock_version = u.old_lv RETURNING id)`
  combined with a final `SELECT count(*) FROM updated_accounts` yields the
  number of accounts that matched their expected `lock_version`. If that
  count is less than `map_size(write_plan.merged_accounts)` we raise
  `Ecto.StaleEntryError` with `action: :update`. The orchestrator (Step 5)
  wraps us in `Repo.transaction/1`, so the raise rolls back the whole
  batch.
  """

  alias DoubleEntryLedger.{Account, BatchProcessor, BatchSerializer}
  alias DoubleEntryLedger.Command.TransactionCommandMap

  @schema_prefix DoubleEntryLedger.Config.schema_prefix()

  @doc """
  Executes the success half of a batched write in one round-trip.

  ## Parameters

    * `write_plan` - output of `BatchProcessor.simulate_batch/2`
    * `repo` - the Ecto repo module
    * `now` - DateTime to use for `inserted_at`/`updated_at`/`posted_at`/
      `processing_completed_at`. Caller supplies it so all rows in the
      batch share the same timestamp.

  Returns `:ok`. Raises `Ecto.StaleEntryError` if any account's
  `lock_version` advanced between fold and write.

  Returns `:ok` immediately (no SQL) when `write_plan.successes == []`.
  """
  @spec write_successes(BatchProcessor.write_plan(), Ecto.Repo.t(), DateTime.t()) :: :ok
  def write_successes(%{successes: []}, _repo, _now), do: :ok

  def write_successes(%{successes: successes, merged_accounts: merged_accounts}, repo, now) do
    successes = assign_ids(successes)
    {sql, params} = build_query(successes, merged_accounts, now)
    %Postgrex.Result{rows: [[accounts_updated]]} = Ecto.Adapters.SQL.query!(repo, sql, params)

    expected = map_size(merged_accounts)

    if accounts_updated == expected do
      :ok
    else
      raise Ecto.StaleEntryError,
        action: :update,
        changeset: Ecto.Changeset.change(%Account{})
    end
  end

  # ── SQL building ─────────────────────────────────────────────────

  # Builds a single SQL statement with multiple data-modifying CTEs that
  # together write all rows for the success group. Returns
  # `{sql_string, params_list}` ready for `Ecto.Adapters.SQL.query!/3`.
  @spec build_query([map()], map(), DateTime.t()) :: {String.t(), [term()]}
  defp build_query(successes, merged_accounts, now) do
    state = %{params: [], idx: 0}

    {tx_sql, state} = build_transactions_cte(successes, now, state)
    {entry_sql, state} = build_entries_cte(successes, now, state)
    {bhe_sql, state} = build_bhes_cte(successes, now, state)
    {journal_sql, state} = build_journals_cte(successes, now, state)
    {lookup_sql, state} = build_lookups_cte(successes, now, state)
    {accounts_sql, state} = build_accounts_cte(merged_accounts, now, state)
    {queue_sql, state} = build_queue_items_cte(successes, now, state)

    ctes =
      [tx_sql, entry_sql, bhe_sql, journal_sql, lookup_sql, accounts_sql, queue_sql]
      |> Enum.reject(&is_nil/1)

    sql =
      "WITH " <>
        Enum.join(ctes, ",\n") <>
        "\nSELECT (SELECT count(*) FROM updated_accounts) AS accounts_updated"

    {sql, Enum.reverse(state.params)}
  end

  # ── transactions CTE ─────────────────────────────────────────────
  defp build_transactions_cte(successes, now, state) do
    {rows, state} =
      Enum.reduce(successes, {[], state}, fn success, {rows, st} ->
        {placeholders, st} =
          push_params(st, [
            uuid(success.transaction_id),
            Atom.to_string(success.status),
            uuid(success.command.instance_id),
            posted_at_for(success.status, now),
            now,
            now
          ])

        cast = "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}, " <>
                 "#{p(placeholders, 2)}::uuid, #{p(placeholders, 3)}::timestamptz, " <>
                 "#{p(placeholders, 4)}::timestamptz, #{p(placeholders, 5)}::timestamptz)"

        {[cast | rows], st}
      end)

    sql = """
    inserted_txs AS (
      INSERT INTO #{table("transactions")}
        (id, status, instance_id, posted_at, inserted_at, updated_at)
      VALUES #{Enum.join(Enum.reverse(rows), ", ")}
      RETURNING id
    )
    """

    {sql, state}
  end

  # ── entries CTE ──────────────────────────────────────────────────
  defp build_entries_cte(successes, now, state) do
    {rows, state} =
      Enum.reduce(successes, {[], state}, fn success, acc ->
        Enum.reduce(success.entries, acc, fn entry, {rows, st} ->
          dumped_value = BatchSerializer.dump_money(entry.value)

          {placeholders, st} =
            push_params(st, [
              uuid(entry.id),
              uuid(success.transaction_id),
              uuid(entry.account_id),
              Atom.to_string(entry.type),
              dumped_value,
              now,
              now
            ])

          cast =
            "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}::uuid, " <>
              "#{p(placeholders, 2)}::uuid, #{p(placeholders, 3)}, " <>
              "#{p(placeholders, 4)}::jsonb, #{p(placeholders, 5)}::timestamptz, " <>
              "#{p(placeholders, 6)}::timestamptz)"

          {[cast | rows], st}
        end)
      end)

    sql = """
    inserted_entries AS (
      INSERT INTO #{table("entries")}
        (id, transaction_id, account_id, type, value, inserted_at, updated_at)
      VALUES #{Enum.join(Enum.reverse(rows), ", ")}
      RETURNING id
    )
    """

    {sql, state}
  end

  # ── balance_history_entries CTE ──────────────────────────────────
  defp build_bhes_cte(successes, now, state) do
    {rows, state} =
      Enum.reduce(successes, {[], state}, fn success, acc ->
        Enum.reduce(success.entries, acc, fn entry, {rows, st} ->
          account_after = entry.account_after
          dumped_posted = BatchSerializer.dump_balance(account_after.posted)
          dumped_pending = BatchSerializer.dump_balance(account_after.pending)

          {placeholders, st} =
            push_params(st, [
              uuid(Ecto.UUID.generate()),
              uuid(account_after.id),
              uuid(entry.id),
              dumped_posted,
              dumped_pending,
              account_after.available,
              now,
              now
            ])

          cast =
            "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}::uuid, " <>
              "#{p(placeholders, 2)}::uuid, #{p(placeholders, 3)}::jsonb, " <>
              "#{p(placeholders, 4)}::jsonb, #{p(placeholders, 5)}::integer, " <>
              "#{p(placeholders, 6)}::timestamptz, #{p(placeholders, 7)}::timestamptz)"

          {[cast | rows], st}
        end)
      end)

    sql = """
    inserted_bhes AS (
      INSERT INTO #{table("balance_history_entries")}
        (id, account_id, entry_id, posted, pending, available, inserted_at, updated_at)
      VALUES #{Enum.join(Enum.reverse(rows), ", ")}
      RETURNING id
    )
    """

    {sql, state}
  end

  # ── journal_events CTE ───────────────────────────────────────────
  defp build_journals_cte(successes, now, state) do
    {rows, state} =
      Enum.reduce(successes, {[], state}, fn success, {rows, st} ->
        journal_event_id = success.journal_event_id
        command_map_dumped = dump_command_map(success.command.command_map)

        {placeholders, st} =
          push_params(st, [
            uuid(journal_event_id),
            uuid(success.command.id),
            uuid(success.transaction_id),
            uuid(success.command.instance_id),
            command_map_dumped,
            now,
            now
          ])

        cast =
          "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}::uuid, " <>
            "#{p(placeholders, 2)}::uuid, #{p(placeholders, 3)}::uuid, " <>
            "#{p(placeholders, 4)}::jsonb, #{p(placeholders, 5)}::timestamptz, " <>
            "#{p(placeholders, 6)}::timestamptz)"

        {[cast | rows], st}
      end)

    sql = """
    inserted_journals AS (
      INSERT INTO #{table("journal_events")}
        (id, command_id, transaction_id, instance_id, command_map, inserted_at, updated_at)
      VALUES #{Enum.join(Enum.reverse(rows), ", ")}
      RETURNING id
    )
    """

    {sql, state}
  end

  # ── pending_transaction_lookup CTE (only :pending successes) ─────
  defp build_lookups_cte(successes, now, state) do
    pending = Enum.filter(successes, &(&1.status == :pending))

    case pending do
      [] ->
        {nil, state}

      _ ->
        {rows, state} =
          Enum.reduce(pending, {[], state}, fn success, {rows, st} ->
            cm = success.command.command_map

            {placeholders, st} =
              push_params(st, [
                uuid(success.command.instance_id),
                cm.source,
                cm.source_idempk,
                uuid(success.command.id),
                uuid(success.transaction_id),
                uuid(success.journal_event_id),
                now,
                now
              ])

            cast =
              "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}::text, " <>
                "#{p(placeholders, 2)}::text, #{p(placeholders, 3)}::uuid, " <>
                "#{p(placeholders, 4)}::uuid, #{p(placeholders, 5)}::uuid, " <>
                "#{p(placeholders, 6)}::timestamptz, #{p(placeholders, 7)}::timestamptz)"

            {[cast | rows], st}
          end)

        sql = """
        inserted_lookups AS (
          INSERT INTO #{table("pending_transaction_lookup")}
            (instance_id, source, source_idempk, command_id, transaction_id, journal_event_id, inserted_at, updated_at)
          VALUES #{Enum.join(Enum.reverse(rows), ", ")}
          ON CONFLICT (source, source_idempk, instance_id)
          DO UPDATE SET
            transaction_id = EXCLUDED.transaction_id,
            journal_event_id = EXCLUDED.journal_event_id
          RETURNING instance_id
        )
        """

        {sql, state}
    end
  end

  # ── accounts UPDATE CTE ──────────────────────────────────────────
  defp build_accounts_cte(merged_accounts, now, state) do
    {rows, state} =
      Enum.reduce(merged_accounts, {[], state}, fn {id, m}, {rows, st} ->
        dumped_posted = BatchSerializer.dump_balance(m.posted)
        dumped_pending = BatchSerializer.dump_balance(m.pending)

        {placeholders, st} =
          push_params(st, [
            uuid(id),
            dumped_posted,
            dumped_pending,
            m.available,
            m.old_lock_version,
            m.new_lock_version
          ])

        cast =
          "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}::jsonb, " <>
            "#{p(placeholders, 2)}::jsonb, #{p(placeholders, 3)}::integer, " <>
            "#{p(placeholders, 4)}::integer, #{p(placeholders, 5)}::integer)"

        {[cast | rows], st}
      end)

    {now_placeholder, state} = push_param(state, now)

    sql = """
    updated_accounts AS (
      UPDATE #{table("accounts")} AS a
      SET posted = u.posted,
          pending = u.pending,
          available = u.available,
          lock_version = u.new_lv,
          updated_at = #{now_placeholder}::timestamptz
      FROM (VALUES #{Enum.join(Enum.reverse(rows), ", ")})
        AS u(id, posted, pending, available, old_lv, new_lv)
      WHERE a.id = u.id AND a.lock_version = u.old_lv
      RETURNING a.id
    )
    """

    {sql, state}
  end

  # ── command_queue_items UPDATE CTE ───────────────────────────────
  defp build_queue_items_cte(successes, now, state) do
    queue_item_ids = Enum.map(successes, &uuid(&1.command.command_queue_item.id))

    {placeholders, state} = push_params(state, [queue_item_ids, now])

    sql = """
    processed_queue_items AS (
      UPDATE #{table("command_queue_items")}
      SET status = 'processed',
          processing_completed_at = #{p(placeholders, 1)}::timestamptz,
          next_retry_after = NULL,
          processor_version = processor_version + 1,
          updated_at = #{p(placeholders, 1)}::timestamptz
      WHERE id = ANY(#{p(placeholders, 0)}::uuid[])
      RETURNING id
    )
    """

    {sql, state}
  end

  # ── helpers ──────────────────────────────────────────────────────

  # Stamp each success record with a generated `:journal_event_id` and
  # each of its entries with a generated `:id` so all CTEs can reference
  # the same UUIDs without ordering between INSERT and SELECT.
  defp assign_ids(successes) do
    Enum.map(successes, fn success ->
      entries =
        Enum.map(success.entries, fn entry ->
          Map.put_new_lazy(entry, :id, &Ecto.UUID.generate/0)
        end)

      success
      |> Map.put(:entries, entries)
      |> Map.put_new_lazy(:journal_event_id, &Ecto.UUID.generate/0)
    end)
  end

  defp table(name), do: "\"#{@schema_prefix}\".#{name}"

  # Postgrex expects UUIDs as 16-byte binaries; Ecto schema fields hold
  # them as canonical strings. Convert at the bind boundary so the SQL
  # builders can read `*.id`/`*.account_id` etc. naturally.
  defp uuid(<<_::binary-size(16)>> = bin), do: bin
  defp uuid(str) when is_binary(str), do: Ecto.UUID.dump!(str)

  defp posted_at_for(:posted, now), do: now
  defp posted_at_for(:pending, _now), do: nil

  # Dump a TransactionCommandMap struct to a JSONB-encodable map matching
  # what the legacy CommandMap.dump path produces.
  defp dump_command_map(%TransactionCommandMap{} = cm), do: TransactionCommandMap.to_map(cm)

  # Push a single parameter to the bind list, returning its placeholder
  # string ("$N") and the new state.
  defp push_param(%{params: params, idx: idx}, value) do
    new_idx = idx + 1
    {"$#{new_idx}", %{params: [value | params], idx: new_idx}}
  end

  # Push a list of parameters; returns the list of placeholders for them
  # in the order pushed.
  defp push_params(state, values) do
    {placeholders_rev, state} =
      Enum.reduce(values, {[], state}, fn v, {acc, st} ->
        {ph, st} = push_param(st, v)
        {[ph | acc], st}
      end)

    {Enum.reverse(placeholders_rev), state}
  end

  # Index helper for the row-local placeholder list returned by push_params.
  defp p(placeholders, i), do: Enum.at(placeholders, i)
end
