defmodule DoubleEntryLedger.Stores.BatchTransactionStoreHelper do
  @moduledoc """
  Executes the **success** half of a batched write — one CTE per
  Postgres round-trip — for a batch of `:create_transaction` and
  `:update_transaction` commands.

  Consumes the output of `BatchProcessor.simulate_batch/2`. Failure
  handling lives in the sibling failure-UPDATE writer (Step 4).
  Wrapping in a `Repo.transaction/1` is the orchestrator's
  responsibility (Step 5).

  Behaviour-equivalent to the legacy `build_create/4` +
  `handle_build_transaction/3` path AND the legacy
  `TransactionStoreHelper.build_update/5` path: same row shapes, same
  optimistic-concurrency semantics on accounts, and matching
  `pending_transaction_lookup` lifecycle:

    * INSERT/upsert on `:pending` create successes (`inserted_lookups`).
    * DELETE on update successes whose transition is terminal
      (`:posted` / `:archived`) — see `deleted_lookups`. Mirrors
      legacy `delete_lookup_on_terminal/4`.
    * No write for `:pending_to_pending` updates (row stays as the
      tx remains `:pending`).

  ## Strategy

  All UUIDs (transaction, entry, BHE, journal_event, lookup) are
  pre-generated by the orchestrator (`BatchProcessor.run_batch/2`)
  before the fold runs, so each CTE is independent — none references
  another CTE's `RETURNING`. The CTE bundle is just round-trip
  batching, not value chaining. This avoids tying CTE evaluation order
  to row order constraints.

  Successes are partitioned by `:action` at the top of `build_query/3`:
  `inserted_successes` (creates) feed the INSERT CTEs; `updated_successes`
  (updates) feed the new UPDATE CTEs. BHE, journal_event, account-update,
  and queue-mark CTEs accept the whole list (both create and update entries
  produce BHE/journal rows; both create and update queue items are marked
  `:processed`).

  ## Input contract

  Each success record MUST already carry:
    * `:action` — `:create_transaction` or `:update_transaction`
    * `:transaction_id` (set by the fold; for updates this is the existing tx's id)
    * `:journal_event_id` (set by the orchestrator pre-fold)
    * `:id` on every entry (creates: pre-generated; updates: re-used existing entry id)
    * `:transition` only on update success records

  The writer does not generate UUIDs. The BHE id is the only
  exception — it is generated locally per row since it is never
  referenced elsewhere.

  ## Stale lock_version + TOCTOU detection

  Two write-time guards:

    * `updated_accounts AS (UPDATE ... WHERE lock_version = u.old_lv RETURNING id)`
      → `SELECT count(*) FROM updated_accounts` must equal
      `map_size(merged_accounts)`. Otherwise an account's `lock_version`
      moved between fold and write.
    * `updated_transactions AS (UPDATE ... WHERE t.status = 'pending' RETURNING t.id)`
      → `SELECT count(*) FROM updated_transactions` must equal
      `length(updated_successes)`. Otherwise a target transaction's
      status flipped externally between read and write (e.g., a parallel
      direct-API write transitioned it to `:posted` / `:archived`). Stronger
      than legacy, which has only a read-time `validate_state_transition/1`
      check and no write-time guard.
    * Queue-item updates match both `processor_id` and `processor_version`,
      and their updated row count must equal the expected command count.
      Otherwise a replacement processor owns at least one command.

  Account or transaction mismatches raise `Ecto.StaleEntryError` with
  `action: :update`. Queue ownership mismatches raise
  `CommandQueue.OwnershipError`.
  The orchestrator (Step 5) wraps us in `Repo.transaction/1`, so the
  raise rolls back the whole batch.
  """

  alias DoubleEntryLedger.{
    Account,
    BatchProcessor,
    BatchSerializer,
    Command,
    CommandQueueItem,
    Transaction
  }

  alias DoubleEntryLedger.Command.TransactionCommandMap
  alias DoubleEntryLedger.CommandQueue.{OwnershipError, Scheduling}

  @schema_prefix DoubleEntryLedger.Config.schema_prefix()

  # `next_retry_after` is only set for a dependency wait that carries the
  # create command's database-written retry time; every other retry supplies
  # `retry_delay_seconds` and lets the queue trigger compute the deadline on
  # the database clock. Dead letters set both to nil.
  @type planned_failure :: %{
          required(:command) => Command.t(),
          required(:status) => CommandQueueItem.state(),
          required(:next_retry_after) => DateTime.t() | nil,
          required(:retry_delay_seconds) => pos_integer() | nil,
          required(:error) => map(),
          required(:processor_id_after) => String.t() | nil
        }

  @doc """
  Executes the success half of a batched write in one round-trip.

  ## Parameters

    * `write_plan` - output of `BatchProcessor.simulate_batch/2`
    * `repo` - the Ecto repo module
    * `now` - DateTime used for transaction, entry, journal-event, and
      balance-history timestamps. Queue processing timestamps come from
      PostgreSQL.

  Returns `:ok`. Raises `Ecto.StaleEntryError` if an account or transaction
  changed between fold and write, or `CommandQueue.OwnershipError` if command
  ownership changed.

  Returns `:ok` immediately (no SQL) when `write_plan.successes == []`.
  """
  @spec write_successes(BatchProcessor.write_plan(), Ecto.Repo.t(), DateTime.t()) :: :ok
  def write_successes(%{successes: []}, _repo, _now), do: :ok

  def write_successes(%{successes: successes, merged_accounts: merged_accounts}, repo, now) do
    {inserted_successes, updated_successes} =
      Enum.split_with(successes, &(&1.action == :create_transaction))

    {sql, params} =
      build_query(successes, inserted_successes, updated_successes, merged_accounts, now)

    %Postgrex.Result{rows: [[accounts_updated, transactions_updated, queue_items_updated]]} =
      repo.query!(sql, params)

    expected_accounts = map_size(merged_accounts)
    expected_tx_updates = length(updated_successes)
    expected_queue_updates = length(successes)

    cond do
      queue_items_updated != expected_queue_updates ->
        raise OwnershipError, batch_command_ids: Enum.map(successes, & &1.command.id)

      accounts_updated != expected_accounts or transactions_updated != expected_tx_updates ->
        raise Ecto.StaleEntryError,
          action: :update,
          changeset: Ecto.Changeset.change(%Account{})

      true ->
        :ok
    end
  end

  @doc """
  Executes the failure half of a batched write in one round-trip.

  Dependency waits return to `:pending` with a retry deadline without consuming
  retry budget. Missing or dead-lettered create dependencies immediately
  dead-letter the update. Other failures ask
  `CommandQueue.Scheduling.build_schedule_retry_with_reason/3` whether the
  command should be retried or dead-lettered based on `retry_count`:

    * Dependency-wait branch → queue row marked `:pending` without changing
      `retry_count`. When the create command already has a database-written
      `next_retry_after` the update inherits it; otherwise
      `retry_delay_seconds = 1`.
    * Retry branch → queue row marked `:failed`, `retry_delay_seconds` set to
      the exponential-backoff delay.
    * Dead-letter branch → queue row marked `:dead_letter`,
      `next_retry_after` and `retry_delay_seconds` cleared (`NULL`).

  Retry deadlines are computed by PostgreSQL: the UPDATE writes both
  `next_retry_after` and `retry_delay_seconds`, and the queue trigger
  (migration 5) turns a non-`NULL` delay into
  `next_retry_after = database_now + delay`, clearing the delay in the same
  write. No application clock is involved in retry timing.

  In every case the new error payload is prepended to the `errors` JSONB
  array. `retry_count` is not touched here; it is bumped at claim time by
  `Scheduling.claim_batch_for_processing/3`.
  `processor_version` fences the write against a replacement owner and is
  advanced by a successful transition. On the `:failed` branch we additionally clear
  `processor_id` (mirroring `schedule_retry_changeset/4`); on the
  `:dead_letter` branch we preserve it (mirroring `dead_letter_changeset/2`).

  ## Parameters

    * `failures` - list of `t:BatchProcessor.failure_record/0`
    * `repo` - the Ecto repo module
    * `now` - DateTime used as the `inserted_at` timestamp inside each error
      payload. Queue completion time and retry deadlines come from
      PostgreSQL.

  Returns the persisted failure plans, or `[]` immediately without SQL when
  `failures == []`. The caller emits telemetry after its transaction commits.
  """
  @spec write_failures([BatchProcessor.failure_record()], Ecto.Repo.t(), DateTime.t()) ::
          [planned_failure()]
  def write_failures([], _repo, _now), do: []

  def write_failures(failures, repo, now) when is_list(failures) do
    plans = plan_failures(failures, now)
    {sql, params} = build_failure_query(plans)
    %Postgrex.Result{num_rows: updated} = repo.query!(sql, params)

    if updated == length(failures) do
      plans
    else
      raise OwnershipError, batch_command_ids: Enum.map(failures, & &1.command.id)
    end
  end

  # ── SQL building ─────────────────────────────────────────────────

  # Builds a single SQL statement with multiple data-modifying CTEs that
  # together write all rows for the success group. Returns
  # `{sql_string, params_list}` ready for `repo.query!/2`.
  #
  # The CTEs that operate on a partitioned slice take `inserted_successes`
  # (creates) or `updated_successes` (updates); CTEs that emit one row
  # per entry-or-command across both kinds take the whole list.
  @spec build_query([map()], [map()], [map()], map(), DateTime.t()) ::
          {String.t(), [term()]}
  defp build_query(successes, inserted_successes, updated_successes, merged_accounts, now) do
    state = %{params: [], idx: 0}

    {tx_sql, state} = build_transactions_cte(inserted_successes, now, state)
    {entry_sql, state} = build_entries_cte(inserted_successes, now, state)
    {bhe_sql, state} = build_bhes_cte(successes, now, state)
    {journal_sql, state} = build_journals_cte(successes, now, state)
    {lookup_sql, state} = build_lookups_cte(inserted_successes, now, state)
    {accounts_sql, state} = build_accounts_cte(merged_accounts, now, state)
    {queue_sql, state} = build_queue_items_cte(successes, state)
    {updated_tx_sql, state} = build_updated_transactions_cte(updated_successes, now, state)
    {updated_entries_sql, state} = build_updated_entries_cte(updated_successes, now, state)
    {deleted_lookups_sql, state} = build_deleted_lookups_cte(updated_successes, state)

    ctes =
      [
        tx_sql,
        entry_sql,
        bhe_sql,
        journal_sql,
        lookup_sql,
        accounts_sql,
        queue_sql,
        updated_tx_sql,
        updated_entries_sql,
        deleted_lookups_sql
      ]
      |> Enum.reject(&is_nil/1)

    # When there are no updates, the `updated_transactions` CTE is omitted
    # from the WITH clause; emit a literal 0 so the consumer always
    # destructures two columns.
    transactions_updated_expr =
      if updated_successes == [],
        do: "0",
        else: "(SELECT count(*) FROM updated_transactions)"

    sql =
      "WITH " <>
        Enum.join(ctes, ",\n") <>
        "\nSELECT " <>
        "(SELECT count(*) FROM updated_accounts) AS accounts_updated, " <>
        "#{transactions_updated_expr} AS transactions_updated, " <>
        "(SELECT count(*) FROM processed_queue_items) AS queue_items_updated"

    {sql, Enum.reverse(state.params)}
  end

  # ── transactions CTE ─────────────────────────────────────────────
  defp build_transactions_cte([], _now, state), do: {nil, state}

  defp build_transactions_cte(inserted_successes, now, state) do
    {values_sql, state} =
      accumulate_value_rows(inserted_successes, state, fn success, st ->
        {placeholders, st} =
          push_params(st, [
            uuid(success.transaction_id),
            Atom.to_string(success.status),
            uuid(success.command.instance_id),
            posted_at_for(success.status, now),
            now,
            now
          ])

        cast =
          "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}, " <>
            "#{p(placeholders, 2)}::uuid, #{timestamp(p(placeholders, 3))}, " <>
            "#{timestamp(p(placeholders, 4))}, #{timestamp(p(placeholders, 5))})"

        {cast, st}
      end)

    sql = """
    inserted_txs AS (
      INSERT INTO #{table("transactions")}
        (id, status, instance_id, posted_at, inserted_at, updated_at)
      VALUES #{values_sql}
      RETURNING id
    )
    """

    {sql, state}
  end

  # ── entries CTE ──────────────────────────────────────────────────
  defp build_entries_cte([], _now, state), do: {nil, state}

  defp build_entries_cte(successes, now, state) do
    entries_with_tx =
      Enum.flat_map(successes, fn s -> Enum.map(s.entries, &{s.transaction_id, &1}) end)

    {values_sql, state} =
      accumulate_value_rows(entries_with_tx, state, fn {tx_id, entry}, st ->
        {placeholders, st} =
          push_params(st, [
            uuid(entry.id),
            uuid(tx_id),
            uuid(entry.account_id),
            Atom.to_string(entry.type),
            BatchSerializer.dump_money(entry.value),
            now,
            now
          ])

        cast =
          "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}::uuid, " <>
            "#{p(placeholders, 2)}::uuid, #{p(placeholders, 3)}, " <>
            "#{p(placeholders, 4)}::jsonb, #{timestamp(p(placeholders, 5))}, " <>
            "#{timestamp(p(placeholders, 6))})"

        {cast, st}
      end)

    sql = """
    inserted_entries AS (
      INSERT INTO #{table("entries")}
        (id, transaction_id, account_id, type, value, inserted_at, updated_at)
      VALUES #{values_sql}
      RETURNING id
    )
    """

    {sql, state}
  end

  # ── balance_history_entries CTE ──────────────────────────────────
  defp build_bhes_cte(successes, now, state) do
    entries = Enum.flat_map(successes, & &1.entries)

    {values_sql, state} =
      accumulate_value_rows(entries, state, fn entry, st ->
        account_after = entry.account_after

        {placeholders, st} =
          push_params(st, [
            uuid(Ecto.UUID.generate()),
            uuid(account_after.id),
            uuid(entry.id),
            BatchSerializer.dump_balance(account_after.posted),
            BatchSerializer.dump_balance(account_after.pending),
            account_after.available,
            now,
            now
          ])

        cast =
          "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}::uuid, " <>
            "#{p(placeholders, 2)}::uuid, #{p(placeholders, 3)}::jsonb, " <>
            "#{p(placeholders, 4)}::jsonb, #{p(placeholders, 5)}::bigint, " <>
            "#{timestamp(p(placeholders, 6))}, #{timestamp(p(placeholders, 7))})"

        {cast, st}
      end)

    sql = """
    inserted_bhes AS (
      INSERT INTO #{table("balance_history_entries")}
        (id, account_id, entry_id, posted, pending, available, inserted_at, updated_at)
      VALUES #{values_sql}
      RETURNING id
    )
    """

    {sql, state}
  end

  # ── journal_events CTE ───────────────────────────────────────────
  defp build_journals_cte(successes, now, state) do
    {values_sql, state} =
      accumulate_value_rows(successes, state, fn success, st ->
        {placeholders, st} =
          push_params(st, [
            uuid(success.journal_event_id),
            uuid(success.command.id),
            uuid(success.transaction_id),
            uuid(success.command.instance_id),
            dump_command_map(success.command.command_map),
            now,
            now
          ])

        cast =
          "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}::uuid, " <>
            "#{p(placeholders, 2)}::uuid, #{p(placeholders, 3)}::uuid, " <>
            "#{p(placeholders, 4)}::jsonb, #{timestamp(p(placeholders, 5))}, " <>
            "#{timestamp(p(placeholders, 6))})"

        {cast, st}
      end)

    sql = """
    inserted_journals AS (
      INSERT INTO #{table("journal_events")}
        (id, command_id, transaction_id, instance_id, command_map, inserted_at, updated_at)
      VALUES #{values_sql}
      RETURNING id
    )
    """

    {sql, state}
  end

  # ── pending_transaction_lookup CTE (only :pending successes) ─────
  defp build_lookups_cte(successes, now, state) do
    pending = Enum.filter(successes, &(&1.status == :pending))

    case pending do
      [] ->
        {nil, state}

      _ ->
        {values_sql, state} =
          accumulate_value_rows(pending, state, fn success, st ->
            cm = success.command.command_map

            {placeholders, st} =
              push_params(st, [
                uuid(success.command.instance_id),
                cm.source,
                cm.source_idempk,
                uuid(success.command.id),
                uuid(success.transaction_id),
                uuid(success.journal_event_id),
                now,
                now
              ])

            cast =
              "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}::text, " <>
                "#{p(placeholders, 2)}::text, #{p(placeholders, 3)}::uuid, " <>
                "#{p(placeholders, 4)}::uuid, #{p(placeholders, 5)}::uuid, " <>
                "#{timestamp(p(placeholders, 6))}, #{timestamp(p(placeholders, 7))})"

            {cast, st}
          end)

        # The placeholder-reservation pattern: command persistence
        # inserts a `pending_transaction_lookup` row with
        # `transaction_id = NULL` at command-map time (the unique index
        # on `(instance_id, source, source_idempk)` doubles as the
        # idempotency guard). The writer then upserts to fill in
        # `transaction_id` / `journal_event_id` once the tx commits.
        # `DO UPDATE` is therefore the load-bearing arm, not a silent
        # overwrite — by the time a CONFLICT fires, the existing row
        # is the matching placeholder and EXCLUDED.* carries the
        # freshly-committed ids.
        sql = """
        inserted_lookups AS (
          INSERT INTO #{table("pending_transaction_lookup")}
            (instance_id, source, source_idempk, command_id, transaction_id, journal_event_id, inserted_at, updated_at)
          VALUES #{values_sql}
          ON CONFLICT (source, source_idempk, instance_id)
          DO UPDATE SET
            transaction_id = EXCLUDED.transaction_id,
            journal_event_id = EXCLUDED.journal_event_id
          RETURNING instance_id
        )
        """

        {sql, state}
    end
  end

  # ── accounts UPDATE CTE ──────────────────────────────────────────
  defp build_accounts_cte(merged_accounts, now, state) do
    {values_sql, state} =
      accumulate_value_rows(merged_accounts, state, fn {id, m}, st ->
        {placeholders, st} =
          push_params(st, [
            uuid(id),
            BatchSerializer.dump_balance(m.posted),
            BatchSerializer.dump_balance(m.pending),
            m.available,
            m.old_lock_version,
            m.new_lock_version
          ])

        # `lock_version` columns are currently int4; cast as ::bigint
        # anyway so the parameter cast is forward-compatible if the
        # column is later widened (matching posted/pending/available
        # which were widened in migration 5). PG auto-coerces the assignment.
        cast =
          "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}::jsonb, " <>
            "#{p(placeholders, 2)}::jsonb, #{p(placeholders, 3)}::bigint, " <>
            "#{p(placeholders, 4)}::bigint, #{p(placeholders, 5)}::bigint)"

        {cast, st}
      end)

    {now_placeholder, state} = push_param(state, now)

    sql = """
    updated_accounts AS (
      UPDATE #{table("accounts")} AS a
      SET posted = u.posted,
          pending = u.pending,
          available = u.available,
          lock_version = u.new_lv,
          updated_at = #{timestamp(now_placeholder)}
      FROM (VALUES #{values_sql})
        AS u(id, posted, pending, available, old_lv, new_lv)
      WHERE a.id = u.id AND a.lock_version = u.old_lv
      RETURNING a.id
    )
    """

    {sql, state}
  end

  # ── updated_transactions UPDATE CTE ──────────────────────────────
  # Status transitions for the three update transitions:
  #   :pending → :posted   (sets posted_at = now)
  #   :pending → :pending  (no-op on status; posted_at stays NULL)
  #   :pending → :archived (sets status = 'archived'; posted_at stays NULL)
  # The `WHERE t.status = 'pending'` predicate is the write-time TOCTOU
  # guard described in the module docs. The post-write
  # `count(*) FROM updated_transactions` is compared against
  # `length(updated_successes)` by `write_successes/3`.
  defp build_updated_transactions_cte([], _now, state), do: {nil, state}

  defp build_updated_transactions_cte(updated_successes, now, state) do
    {rows, state} =
      Enum.reduce(updated_successes, {[], state}, fn success, {rows, st} ->
        {placeholders, st} =
          push_params(st, [
            uuid(success.transaction_id),
            Atom.to_string(success.status),
            posted_at_for(success.status, now)
          ])

        cast =
          "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}, " <>
            "#{timestamp(p(placeholders, 2))})"

        {[cast | rows], st}
      end)

    {now_placeholder, state} = push_param(state, now)

    sql = """
    updated_transactions AS (
      UPDATE #{table("transactions")} AS t
      SET status = u.status,
          posted_at = u.posted_at,
          updated_at = #{timestamp(now_placeholder)}
      FROM (VALUES #{Enum.join(Enum.reverse(rows), ", ")})
        AS u(id, status, posted_at)
      WHERE t.id = u.id AND t.status = 'pending'
      RETURNING t.id
    )
    """

    {sql, state}
  end

  # ── updated_entries UPDATE CTE ───────────────────────────────────
  # One row per entry across all update successes. Entry IDs are re-used
  # from the existing transaction's entries (filled in by
  # `enrich_updates_with_existing/2`), and the value is the NEW payload
  # value. The pre-write OLD value is reconstructable from the BHE chain
  # if needed for audit.
  defp build_updated_entries_cte([], _now, state), do: {nil, state}

  defp build_updated_entries_cte(updated_successes, now, state) do
    {rows, state} =
      Enum.reduce(updated_successes, {[], state}, fn success, acc ->
        Enum.reduce(success.entries, acc, fn entry, {rows, st} ->
          dumped_value = BatchSerializer.dump_money(entry.value)

          {placeholders, st} =
            push_params(st, [
              uuid(entry.id),
              dumped_value
            ])

          cast =
            "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}::jsonb)"

          {[cast | rows], st}
        end)
      end)

    {now_placeholder, state} = push_param(state, now)

    sql = """
    updated_entries AS (
      UPDATE #{table("entries")} AS e
      SET value = u.value,
          updated_at = #{timestamp(now_placeholder)}
      FROM (VALUES #{Enum.join(Enum.reverse(rows), ", ")})
        AS u(id, value)
      WHERE e.id = u.id
      RETURNING e.id
    )
    """

    {sql, state}
  end

  # ── deleted_lookups CTE ──────────────────────────────────────────
  # Deletes `pending_transaction_lookup` rows for updates whose new
  # status is terminal (`:posted` or `:archived`). The lookup row is
  # only useful while the tx remains `:pending`; once it transitions
  # out, the row is dead weight. Mirrors the legacy path's
  # `delete_lookup_on_terminal/4` so the two stay byte-equal.
  defp build_deleted_lookups_cte(updated_successes, state) do
    terminal = Enum.filter(updated_successes, &Transaction.terminal?(&1.status))

    case terminal do
      [] ->
        {nil, state}

      _ ->
        {placeholders, state} =
          push_params(state, Enum.map(terminal, &uuid(&1.transaction_id)))

        id_list = Enum.map_join(placeholders, ", ", &"#{&1}::uuid")

        sql = """
        deleted_lookups AS (
          DELETE FROM #{table("pending_transaction_lookup")}
          WHERE transaction_id IN (#{id_list})
          RETURNING transaction_id
        )
        """

        {sql, state}
    end
  end

  # ── command_queue_items UPDATE CTE ───────────────────────────────
  defp build_queue_items_cte(successes, state) do
    {rows, state} =
      Enum.reduce(successes, {[], state}, fn success, {rows, st} ->
        queue_item = success.command.command_queue_item

        {placeholders, st} =
          push_params(st, [
            uuid(queue_item.id),
            queue_item.processor_id,
            queue_item.processor_version
          ])

        cast =
          "(#{p(placeholders, 0)}::uuid, #{p(placeholders, 1)}::text, " <>
            "#{p(placeholders, 2)}::integer)"

        {[cast | rows], st}
      end)

    sql = """
    processed_queue_items AS (
      UPDATE #{table("command_queue_items")} AS c
      SET status = 'processed',
          next_retry_after = NULL,
          processor_version = c.processor_version + 1
      FROM (VALUES #{Enum.join(Enum.reverse(rows), ", ")})
        AS u(id, processor_id, processor_version)
      WHERE c.id = u.id
        AND c.processor_id IS NOT DISTINCT FROM u.processor_id
        AND c.processor_version = u.processor_version
      RETURNING c.id
    )
    """

    {sql, state}
  end

  # ── failure UPDATE builder ───────────────────────────────────────

  # Builds a single batched UPDATE statement that, for each failed
  # command, marks the queue row `:pending`, `:failed`, or `:dead_letter`
  # (per `compute_failure_outcome/1`). The new error payload is prepended,
  # matching `CommandQueueItem.build_errors/2`'s latest-error-first contract.
  defp plan_failures(failures, now) do
    Enum.map(failures, fn failure ->
      command = failure.command
      {status, next_retry_after, retry_delay_seconds} = compute_failure_outcome(failure)

      # Mirror the legacy changesets: retries release their claim, while
      # terminal dead-letter transitions retain the processor identifier.
      processor_id_after =
        case status do
          :pending -> command.command_queue_item.processor_id
          :failed -> nil
          :dead_letter -> command.command_queue_item.processor_id
        end

      %{
        command: command,
        status: status,
        next_retry_after: next_retry_after,
        retry_delay_seconds: retry_delay_seconds,
        error: error_payload(failure.reason, now),
        processor_id_after: processor_id_after
      }
    end)
  end

  @spec build_failure_query([planned_failure()]) :: {String.t(), [term()]}
  defp build_failure_query(plans) do
    state = %{params: [], idx: 0}

    {rows, state} =
      Enum.reduce(plans, {[], state}, fn plan, {rows, st} ->
        queue_item = plan.command.command_queue_item

        {placeholders, st} =
          push_params(st, [
            uuid(queue_item.id),
            Atom.to_string(plan.status),
            plan.processor_id_after,
            plan.error,
            plan.next_retry_after,
            plan.retry_delay_seconds,
            queue_item.processor_id,
            queue_item.processor_version
          ])

        cast =
          "(#{p(placeholders, 0)}::uuid, " <>
            "#{p(placeholders, 1)}::text, " <>
            "#{p(placeholders, 2)}::text, " <>
            "#{p(placeholders, 3)}::jsonb, " <>
            "#{timestamp(p(placeholders, 4))}, " <>
            "#{p(placeholders, 5)}::integer, " <>
            "#{p(placeholders, 6)}::text, " <>
            "#{p(placeholders, 7)}::integer)"

        {[cast | rows], st}
      end)

    # The queue trigger converts a non-NULL retry_delay_seconds into
    # next_retry_after on the database clock and clears the delay.
    sql = """
    UPDATE #{table("command_queue_items")} AS c
    SET status = u.status,
        errors = jsonb_build_array(u.new_error) || COALESCE(c.errors, '[]'::jsonb),
        next_retry_after = u.next_retry_after,
        retry_delay_seconds = u.retry_delay_seconds,
        processor_id = u.processor_id_after,
        processor_version = c.processor_version + 1
    FROM (VALUES #{Enum.join(Enum.reverse(rows), ", ")})
      AS u(
        id,
        status,
        processor_id_after,
        new_error,
        next_retry_after,
        retry_delay_seconds,
        expected_processor_id,
        processor_version
      )
    WHERE c.id = u.id
      AND c.processor_id IS NOT DISTINCT FROM u.expected_processor_id
      AND c.processor_version = u.processor_version
    """

    {sql, Enum.reverse(state.params)}
  end

  # Dependency waits and ordinary failures use Scheduling as the source of
  # truth for retry limits. Same-batch ordering waits remain pending because
  # their prerequisite is committed by this batch. Terminal dependency
  # failures are dead-lettered immediately. Other failures use the legacy
  # `Scheduling.build_schedule_retry_with_reason/3` as the source of truth.
  #
  # The legacy helper produces:
  #   * `schedule_retry_changeset` (status = `:failed`, retry_delay_seconds
  #     set) when `retry_count < max_retries`
  #   * `dead_letter_changeset` (status = `:dead_letter`, next_retry_after
  #     nil) when `retry_count >= max_retries`
  #
  # Both branches `put_assoc(:command_queue_item, ...)`, so we always
  # reach the inner changeset and dispatch on its `:status` change.
  #
  # Returns `{status, next_retry_after, retry_delay_seconds}`; exactly one of
  # the two timing values is non-nil for a retry, both are nil for a dead
  # letter.
  @spec compute_failure_outcome(BatchProcessor.failure_record()) ::
          {:pending, DateTime.t(), nil}
          | {:pending, nil, 1}
          | {:failed, nil, pos_integer()}
          | {:dead_letter, nil, nil}
  defp compute_failure_outcome(%{reason: reason} = failure)
       when reason == :create_command_not_processed or
              (is_tuple(reason) and
                 elem(reason, 0) in [:create_pending_in_batch, :duplicate_update_in_batch]) do
    dependency_wait_outcome(Map.get(failure, :next_retry_after))
  end

  defp compute_failure_outcome(%{reason: reason})
       when reason in [:create_command_not_found, :create_command_in_dead_letter],
       do: {:dead_letter, nil, nil}

  defp compute_failure_outcome(%{command: command, reason: reason}) do
    cs = Scheduling.build_schedule_retry_with_reason(command, reason_to_message(reason), :failed)
    retry_outcome(cs, command, reason)
  end

  # A dependency wait inherits the create command's database-written retry
  # time when it has one; otherwise it is retried one database second later.
  @spec dependency_wait_outcome(DateTime.t() | nil) ::
          {:pending, DateTime.t(), nil} | {:pending, nil, 1}
  defp dependency_wait_outcome(%DateTime{} = create_next_retry_after),
    do: {:pending, create_next_retry_after, nil}

  defp dependency_wait_outcome(nil), do: {:pending, nil, 1}

  defp retry_outcome(cs, command, reason) do
    qi_cs = Ecto.Changeset.get_change(cs, :command_queue_item)

    case Ecto.Changeset.get_change(qi_cs, :status) do
      :dead_letter ->
        {:dead_letter, nil, nil}

      :failed ->
        delay = Ecto.Changeset.get_change(qi_cs, :retry_delay_seconds)

        if is_integer(delay) and delay > 0 do
          {:failed, nil, delay}
        else
          # If the legacy helper produced a `:failed` retry without a
          # positive `retry_delay_seconds`, surface it loudly with full
          # context rather than crash with an opaque MatchError.
          raise """
          compute_failure_outcome: legacy scheduler returned :failed without a positive retry_delay_seconds
            command_id=#{command.id}
            instance_id=#{command.instance_id}
            reason=#{inspect(reason)}
            retry_delay_seconds=#{inspect(delay)}
          """
        end
    end
  end

  # Build a JSONB-encodable error map mirroring the shape of
  # `Command.ErrorMap.build_error/1` (`%{message, inserted_at}`).
  @spec error_payload(BatchProcessor.failure_reason(), DateTime.t()) :: %{
          message: String.t(),
          inserted_at: DateTime.t()
        }
  defp error_payload(reason, now) do
    %{message: reason_to_message(reason), inserted_at: now}
  end

  @spec reason_to_message(term()) :: String.t()
  defp reason_to_message({:unbalanced}), do: "batch fold: entries do not balance"

  defp reason_to_message({:account_not_found, account_id}),
    do: "batch fold: account not found: #{account_id}"

  defp reason_to_message({:balance_change_error, field, message}),
    do: "#{field}: #{message}"

  defp reason_to_message({:unsupported_action, action}),
    do: "batch: unsupported action: #{action}"

  defp reason_to_message({:transformer_error, reason}),
    do: "batch transformer: #{reason}"

  defp reason_to_message({:create_pending_in_batch, create_command_id}),
    do:
      "batch: create command (#{create_command_id}) for this idempotency key is in the same batch — retry after it commits"

  defp reason_to_message({:duplicate_update_in_batch, first_command_id}),
    do:
      "batch: another update (#{first_command_id}) on the same target transaction is in the same batch — retry after it commits"

  defp reason_to_message(:create_command_not_found),
    do: "update: original create command not found"

  defp reason_to_message(:create_command_in_dead_letter),
    do: "update: original create command is in dead_letter"

  defp reason_to_message(:create_command_not_processed),
    do: "update: original create command has not been processed yet"

  defp reason_to_message(:transaction_not_pending),
    do: "update: target transaction is not in :pending status"

  defp reason_to_message(:entry_count_mismatch),
    do: "update: payload entry count does not match the existing transaction"

  defp reason_to_message(:entry_account_mismatch),
    do: "update: payload entry references an account not in the existing transaction"

  defp reason_to_message(:entry_type_changed),
    do: "update: payload entry changes the debit/credit type of an existing entry"

  defp timestamp(placeholder), do: "#{placeholder}::timestamp"

  # Intentional no catch-all: an unmatched reason raises FunctionClauseError
  # at the call site, which surfaces the new reason in production logs and
  # in Dialyzer output. Add an explicit clause when introducing a new
  # `failure_reason/0` variant rather than letting it ship with a generic
  # "batch: foo" string.

  # ── helpers ──────────────────────────────────────────────────────

  defp table(name), do: "\"#{@schema_prefix}\".#{name}"

  # Postgrex expects UUIDs as 16-byte binaries; Ecto schema fields hold
  # them as canonical strings. Convert at the bind boundary so the SQL
  # builders can read `*.id`/`*.account_id` etc. naturally.
  defp uuid(<<_::binary-size(16)>> = bin), do: bin
  defp uuid(str) when is_binary(str), do: Ecto.UUID.dump!(str)

  defp posted_at_for(:posted, now), do: now
  defp posted_at_for(:pending, _now), do: nil
  defp posted_at_for(:archived, _now), do: nil

  # Dump a TransactionCommandMap struct to a JSONB-encodable map matching
  # what the legacy CommandMap.dump path produces.
  defp dump_command_map(%TransactionCommandMap{} = cm), do: TransactionCommandMap.to_map(cm)

  # Push a single parameter to the bind list, returning its placeholder
  # string ("$N") and the new state.
  defp push_param(%{params: params, idx: idx}, value) do
    new_idx = idx + 1
    {"$#{new_idx}", %{params: [value | params], idx: new_idx}}
  end

  # Reduce over `items`, accumulating each row's cast string into a
  # single comma-joined VALUES body. `build_row_fn` receives `(item,
  # state)` and returns `{cast_string, new_state}` after pushing its
  # params via `push_params/2`. Caller wraps the result in its CTE-
  # specific SQL template. Shared scaffolding for ~9 row-style CTE
  # builders (INSERT VALUES and UPDATE FROM VALUES).
  @spec accumulate_value_rows(Enumerable.t(), map(), (term(), map() -> {String.t(), map()})) ::
          {String.t(), map()}
  defp accumulate_value_rows(items, state, build_row_fn) do
    {rows, state} =
      Enum.reduce(items, {[], state}, fn item, {rows_acc, st} ->
        {cast, st} = build_row_fn.(item, st)
        {[cast | rows_acc], st}
      end)

    {Enum.join(Enum.reverse(rows), ", "), state}
  end

  # Push a list of parameters; returns the list of placeholders for them
  # in the order pushed.
  defp push_params(state, values) do
    {placeholders_rev, state} =
      Enum.reduce(values, {[], state}, fn v, {acc, st} ->
        {ph, st} = push_param(st, v)
        {[ph | acc], st}
      end)

    {Enum.reverse(placeholders_rev), state}
  end

  # Index helper for the row-local placeholder list returned by push_params.
  defp p(placeholders, i), do: Enum.at(placeholders, i)
end
